Repository betaflight/betaflight-configurator, pull requests merged in 2018-07, with the labels that each got.

#1106 Updated readme to remove outdated information.
  README.md
Labels: documentation update

#1113 Added buttons for reboot into boot loader and MSC modes.
  locales/en/messages.json
  src/css/tabs/onboard_logging.css
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/setup.js
  src/main.html
  src/tabs/onboard_logging.html
  src/tabs/setup.html
Labels: Needs coordination with betaflight

#1124 Add feedforward
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/adjustments.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight

#1127 Add feedforward to the tooltip and fix some PIDF
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Rebase Required
