Repository betaflight/betaflight-configurator, pull requests merged in 2018-08, with the labels that each got.

#1149 Added querying of Firmware jobs
  locales/en/messages.json
  manifest.json
  src/js/jenkins_loader.js
  src/js/tabs/firmware_flasher.js
Labels: feature

#1146 Added Google analytics collection.
  libraries/analytics.js
  locales/en/messages.json
  manifest.json
  package-lock.json
  package.json
  src/css/tabs/landing.css
  src/js/Analytics.js
  src/js/Features.js
  src/js/backup_restore.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/landing.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/ports.js
  src/main.html
  src/tabs/landing.html
  src/tabs/options.html
  src/tabs/privacy_policy.html
Labels: Tested

#1167 Updated version for 10.4.1.
  manifest.json
  package-lock.json
  package.json
Labels: applied to branch

#1081 Support for OSD blackbox logging status element
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight
