Repository betaflight/betaflight-configurator, pull requests merged in 2019-12, with the labels that each got.

#1831 Add support for "Auto" RC Smoothing derivative type
  locales/en/messages.json
  src/js/tabs/receiver.js
Labels: RN: Improvement

#1839 Added change heatmap to PIDs for the sliders
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/js/utils/css.js
  src/main.html
Labels: RN: Improvement

#1840 Added FUNDING.yml.
  .github/FUNDING.yml
Labels: Housekeeping

#1841 Added .editorconfig file with the main indentation settings
  .editorconfig
Labels: build system improvement

#1843 The PID slider heatmap now works with the dark theme
  src/js/tabs/pid_tuning.js
  src/js/utils/css.js
Labels: RN: Bugfix

#1845 Fixed URL for CP210x driver.
  locales/en/messages.json
Labels: RN: Bugfix

#1846 I18n custom fallback and Portuguese Brazilian language
  assets/windows/installer.nsi
  crowdin.yml
  locales/en/messages.json
  locales/pt_BR/messages.json
  src/js/localization.js
Labels: RN: Improvement
