Repository betaflight/betaflight-configurator, pull requests merged in 2019-10, with the labels that each got.

#1700 fix alignment of vtx tab icon and transponder tab icon also fix wrong vtx icon on active osd tab
  src/css/main.css
Labels: RN: Bugfix

#1702 Fix options menu not opening
  src/js/main.js
Labels: RN: Bugfix

#1703 Fix font manager select box border radius
  src/css/tabs-dark/osd-dark.css
  src/css/tabs/osd.css
Labels: RN: Bugfix

#1705 Modify a translation in zh_CN for Hacktoberfest
  locales/zh_CN/messages.json
Labels: Hacktoberfest

#1706 Modify a translation in zh_CN for Hacktoberfest -2
  locales/zh_CN/messages.json
Labels: Hacktoberfest

#1707 Modify a translation in zh_CN for Hacktoberfest -3
  locales/zh_CN/messages.json
Labels: Hacktoberfest

#1709 Add description for hacktoberfest
  locales/hr/messages.json
Labels: Hacktoberfest

#1710 Add description for hacktoberfest
  locales/hr/messages.json
Labels: Hacktoberfest

#1711 Hacktoberfest contribution @team_translation
  locales/pt/messages.json
Labels: Hacktoberfest

#1712 Some minor cleanup for hacktoberfest
  src/css/tabs/configuration.css
  src/css/tabs/receiver_msp.css
  src/js/jenkins_loader.js
  src/tabs/adjustments.html
  src/tabs/auxiliary.html
  src/tabs/configuration.html
  src/tabs/failsafe.html
  src/tabs/gps.html
  src/tabs/landing.html
  src/tabs/led_strip.html
  src/tabs/logging.html
  src/tabs/motors.html
  src/tabs/onboard_logging.html
  src/tabs/pid_tuning.html
  src/tabs/privacy_policy.html
  src/tabs/receiver.html
  src/tabs/sensors.html
  src/tabs/transponder.html
Labels: Hacktoberfest, RN: Bugfix

#1718 Fix vtx saving
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#1723 Added note about security settings workaround for MacOS X to README.md.
  README.md
Labels: documentation update

#1724 Updated version to 10.6.0.
  manifest.json
  package.json
Labels: Housekeeping

#1725 Added introduction to Unified Targets.
  locales/en/messages.json
  src/css/main.css
  src/js/gui.js
  src/tabs/firmware_flasher.html
Labels: RN: Improvement

#1737 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/pt/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
Labels: Translation

#1734 Fix small typos in English locale
  locales/en/messages.json
Labels: RN: Improvement

#1732 Added a 'gulp release' task to package.json.
  package.json
Labels: build system improvement

#1736 fix some italian texts
  locales/it/messages.json
Labels: Hacktoberfest

#1738 Incremented version to 10.7.0 after release.
  manifest.json
  package.json
Labels: Housekeeping

#1740 Fixed installation instructions for newer MacOS versions.
  README.md
Labels: documentation update

#1659 ISSUE-1592: Fix misaligned sections on VTX with modern flex. Remove gap between TDs in "current values" section
  src/css/tabs/vtx.css
  src/tabs/vtx.html
Labels: RN: Improvement

#1683 Better representation of battery low
  src/css/main.css
  src/js/serial_backend.js
Labels: RN: Improvement

#1714 clean up some more code smells from sonarcloud
  src/css/tabs/adjustments.css
  src/css/tabs/cli.css
  src/css/tabs/configuration.css
  src/css/tabs/failsafe.css
  src/css/tabs/firmware_flasher.css
  src/css/tabs/receiver.css
  src/js/ConfigInserter.js
  src/js/localization.js
Labels: Hacktoberfest

#1715 Refactor pid-tuning -> tabs
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs/pid_tuning.css
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Refactoring

#1726 Fix "switchery" dark theme by using css-variables.
  src/css/main-dark.css
  src/css/main.css
  src/js/gui.js
Labels: Hacktoberfest, RN: Bugfix

#1716 Fix empty tags. Add missing and delete unnecessary tags.
  src/tabs/auxiliary.html
  src/tabs/led_strip.html
  src/tabs/map.html
  src/tabs/onboard_logging.html
  src/tabs/osd.html
  src/tabs/power.html
  src/tabs/receiver.html
  src/tabs/sensors.html
  src/tabs/vtx.html
Labels: RN: Refactoring

#1670 ISSUE-1609: Create communication mechanism between windows, implement…
  src/css/main-dark.css
  src/css/main.css
  src/css/tabs-dark/adjustments-dark.css
  src/css/tabs/adjustments.css
  src/css/tabs/receiver_msp.css
  src/js/DarkTheme.js
  src/js/tabs/receiver.js
  src/js/tabs/receiver_msp.js
  src/js/utils/window_watchers.js
  src/main.html
  src/tabs/receiver_msp.html
Labels: RN: Improvement

#1747 BFC fonts dithered workaround - update readme
  README.md
Labels: documentation update

#1754 Draw throttle position in tuning tab
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#1756 Changed graphics issues README entry to apply to all operating systems.
  README.md
Labels: documentation update

#1757 Disallow selecting text in MSP Receiver to make dragging more convenient
  src/css/tabs/receiver_msp.css
Labels: RN: Improvement

#1758 Add Basque translation
  assets/windows/installer.nsi
  locales/en/messages.json
  locales/eu/messages.json
  src/js/localization.js
Labels: Hacktoberfest, RN: New Language

#1739 Add support for ACC_CALIB arming disabled flag
  locales/en/messages.json
  src/js/tabs/setup.js
Labels: Needs coordination with betaflight, RN: Improvement

#1760 Put the original and the modulated values on the throttle curve
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#1761 Change "OpenLog" to "OpenLager"
  locales/en/messages.json
Labels: RN: Improvement

#1763 Updated versions of dependencies, including NW.js.
  gulpfile.js
  yarn.lock
Labels: RN: Improvement

#1770 remove a duplicate instance of of update_dataflash_global function
  src/js/serial_backend.js
Labels: RN: Refactoring

#1767 Squash all dark theme files into a single file
  src/css/dark-theme.css
  src/css/main-dark.css
  src/css/tabs-dark/adjustments-dark.css
  src/css/tabs-dark/auxiliary-dark.css
  src/css/tabs-dark/cli-dark.css
  src/css/tabs-dark/configuration-dark.css
  src/css/tabs-dark/failsafe-dark.css
  src/css/tabs-dark/firmware_flasher-dark.css
  src/css/tabs-dark/gps-dark.css
  src/css/tabs-dark/help-dark.css
  src/css/tabs-dark/landing-dark.css
  src/css/tabs-dark/led_strip-dark.css
  src/css/tabs-dark/logging-dark.css
  src/css/tabs-dark/motors-dark.css
  src/css/tabs-dark/onboard_logging-dark.css
  src/css/tabs-dark/osd-dark.css
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs-dark/ports-dark.css
  src/css/tabs-dark/power-dark.css
  src/css/tabs-dark/receiver-dark.css
  src/css/tabs-dark/sensors-dark.css
  src/css/tabs-dark/servos-dark.css
  src/css/tabs-dark/setup-dark.css
  src/css/tabs-dark/transponder-dark.css
  src/js/DarkTheme.js
  src/js/tabs/receiver_msp.js
  src/main.html
  src/tabs/receiver_msp.html
Labels: RN: Improvement

#1764 Fix channel limiting
  src/js/tabs/auxiliary.js
Labels: RN: Bugfix

#1765 Fix sliders marker
  src/css/tabs/adjustments.css
  src/css/tabs/auxiliary.css
Labels: RN: Bugfix

#1771 Update messages.json
  locales/lv/messages.json
Labels: Hacktoberfest

#1759 Save vtx_table lua file.
  locales/en/messages.json
  src/js/tabs/vtx.js
  src/tabs/vtx.html
Labels: RN: Improvement

#1677 CliAutocomplete for diff #1630
  src/js/CliAutoComplete.js
Labels: RN: Improvement

#1775 Update messages.json
  locales/lv/messages.json
Labels: Hacktoberfest

#1776 Update messages.json
  locales/lv/messages.json
Labels: Hacktoberfest

#1777 Update messages.json
  locales/lv/messages.json
Labels: Hacktoberfest

#1774 Hide Motor Poles when it is not necessary
  src/js/tabs/configuration.js
Labels: RN: Improvement

#1779 Update messages.json
  locales/zh_CN/messages.json
Labels: Hacktoberfest

#1782 Fix errors about using i18next before its properly initial…
  package.json
  src/js/localization.js
  yarn.lock
Labels: RN: Bugfix

#1783 convert some style manipulation over to class manipulation
  src/css/main.css
  src/js/serial_backend.js
Labels: Cleanup, RN: Refactoring

#1784 Remove font-awesome
  src/css/font-awesome/css/font-awesome.css
  src/css/font-awesome/css/font-awesome.min.css
  src/css/font-awesome/fonts/FontAwesome.otf
  src/css/font-awesome/fonts/fontawesome-webfont.eot
  src/css/font-awesome/fonts/fontawesome-webfont.svg
  src/css/font-awesome/fonts/fontawesome-webfont.ttf
  src/css/font-awesome/fonts/fontawesome-webfont.woff
  src/css/font-awesome/fonts/fontawesome-webfont.woff2
  src/main.html
Labels: RN: Refactoring

#1786 fixed typo made in #1779
  locales/zh_CN/messages.json
Labels: fixes broken build
