Repository betaflight/betaflight-configurator, pull requests merged in 2019-09, with the labels that each got.

#1607 Gyro filtering restructure debug modes
  src/js/tabs/onboard_logging.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1605 Add MSP_MULTIPLE_MSP command
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
Labels: RN: Improvement

#1610 Keep active subtab selected on PID Tuning tab, change displayed data …
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#1611 Added 0 terminator to custom defaults before flashing.
  src/js/ConfigInserter.js
Labels: RN: Bugfix

#1612 Add save/load buttons for the VTX Table
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/vtx.js
  src/tabs/vtx.html
Labels: RN: Improvement

#1613 refactor CSS references to Open Sans font
  src/css/main.css
  src/css/opensans_webfontkit/fonts.css
  src/css/tabs-dark/onboard_logging-dark.css
  src/css/tabs/configuration.css
  src/css/tabs/failsafe.css
  src/css/tabs/landing.css
  src/css/tabs/motors.css
  src/css/tabs/onboard_logging.css
  src/css/tabs/osd.css
  src/css/tabs/pid_tuning.css
  src/css/tabs/ports.css
  src/css/tabs/receiver_msp.css
  src/css/tabs/setup.css
  src/css/tabs/transponder.css
  src/css/tabs/vtx.css
Labels: RN: Improvement

#1614 Removed Dshot1200 protocol.
  src/js/tabs/configuration.js
Labels: Needs coordination with betaflight, RN: Improvement

#1587 initial go at flashing unified target with a config
  locales/en/messages.json
  src/js/port_handler.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#1615 Add warning if Smartaudio port assigned and VTX table not set up
  locales/en/messages.json
  src/js/tabs/ports.js
  src/tabs/ports.html
Labels: RN: Improvement

#1616 Add visual indicator on ARM mode when arming is disabled by the firmware
  locales/en/messages.json
  src/css/tabs/auxiliary.css
  src/js/tabs/auxiliary.js
Labels: RN: Improvement

#1617 Fix dmin on/off calculation and dmin limit
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1618 Fix CSS button at the MSP TX window
  src/css/tabs/receiver_msp.css
  src/tabs/receiver_msp.html
Labels: RN: Bugfix

#1619 Fix vtx table inputs not always responsive
  src/js/tabs/vtx.js
Labels: RN: Improvement

#1622 Move ESC_SENSOR to the ESC/Motor box
  src/js/Features.js
Labels: RN: Improvement

#1623 Fix note spacing
  src/css/main.css
  src/css/tabs/adjustments.css
  src/css/tabs/auxiliary.css
  src/css/tabs/cli.css
  src/css/tabs/configuration.css
  src/css/tabs/failsafe.css
  src/css/tabs/led_strip.css
  src/css/tabs/ports.css
  src/css/tabs/setup.css
  src/tabs/adjustments.html
  src/tabs/auxiliary.html
  src/tabs/cli.html
  src/tabs/configuration.html
  src/tabs/failsafe.html
  src/tabs/led_strip.html
  src/tabs/logging.html
  src/tabs/onboard_logging.html
  src/tabs/osd.html
  src/tabs/pid_tuning.html
  src/tabs/ports.html
  src/tabs/power.html
  src/tabs/receiver.html
  src/tabs/sensors.html
  src/tabs/servos.html
  src/tabs/setup.html
  src/tabs/setup_osd.html
  src/tabs/transponder.html
  src/tabs/vtx.html
Labels: RN: Improvement

#1627 Fix PID tuning tab active subtab
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1598 Add tuning sliders
  locales/en/messages.json
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/tabs/pid_tuning.js
  src/main.html
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1621 Add RPM filter configuration
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/js/tabs/pid_tuning.js
  src/tabs/configuration.html
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: New UI Element

#1628 throw out unused opensans files
  src/css/opensans_webfontkit/opensans-bold-demo.html
  src/css/opensans_webfontkit/opensans-bold-webfont.eot
  src/css/opensans_webfontkit/opensans-bold-webfont.svg
  src/css/opensans_webfontkit/opensans-bolditalic-demo.html
  src/css/opensans_webfontkit/opensans-bolditalic-webfont.eot
  src/css/opensans_webfontkit/opensans-bolditalic-webfont.svg
  src/css/opensans_webfontkit/opensans-italic-demo.html
  src/css/opensans_webfontkit/opensans-italic-webfont.eot
  src/css/opensans_webfontkit/opensans-italic-webfont.svg
  src/css/opensans_webfontkit/opensans-light-demo.html
  src/css/opensans_webfontkit/opensans-light-webfont.eot
  src/css/opensans_webfontkit/opensans-light-webfont.svg
  src/css/opensans_webfontkit/opensans-regular-demo.html
  src/css/opensans_webfontkit/opensans-regular-webfont.eot
  src/css/opensans_webfontkit/opensans-regular-webfont.svg
  src/css/opensans_webfontkit/opensans-semibold-demo.html
  src/css/opensans_webfontkit/opensans-semibold-webfont.eot
  src/css/opensans_webfontkit/opensans-semibold-webfont.svg
Labels: RN: Improvement

#1629 Fixed duplication of 'gyro_to_use'.
  src/js/fc.js
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#1634 Fix filter subtab line and helpicon spacing
  src/css/tabs/pid_tuning.css
  src/tabs/pid_tuning.html
Labels: RN: Bugfix

#1637 Fixes clicking on helpicon affects input
  src/js/Beepers.js
  src/js/Features.js
  src/tabs/auxiliary.html
  src/tabs/configuration.html
  src/tabs/motors.html
  src/tabs/pid_tuning.html
  src/tabs/vtx.html
Labels: RN: Improvement

#1638 Tuning sliders redesign
  src/css/tabs/pid_tuning.css
Labels: RN: Improvement

#1633 Reorder and make more consistent the Motor/ESC Configuration box
  locales/en/messages.json
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: Improvement

#1639 Fix rateprofiles not working after saving
  src/js/TuningSliders.js
Labels: RN: Bugfix

#1626 Further work: consider versions for unified targets
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: Improvement

#1641 Fix duplicated digital idle help icon
  src/tabs/configuration.html
Labels: RN: Bugfix

#1643 Clean up and improve receiver tab style
  src/css/tabs-dark/receiver-dark.css
  src/css/tabs/receiver.css
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: Improvement

#1644 Add detailed instructions to the VTX Table
  locales/en/messages.json
  src/tabs/vtx.html
Labels: RN: Improvement

#1652 Add 10 and 25 gyro scales to motor tab
  src/js/tabs/motors.js
Labels: RN: Improvement

#1654 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/pt/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
Labels: Translation

#1653 Tuning sliders non expert mode limits
  locales/en/messages.json
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1649 Fix vtx tab animation
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#1650 Add paste from clipboard option to VTX tab
  locales/en/messages.json
  manifest.json
  src/css/main.css
  src/js/Clipboard.js
  src/js/tabs/cli.js
  src/js/tabs/vtx.js
  src/main.html
  src/tabs/vtx.html
Labels: RN: Improvement

#1651 Added dialog to offer resetting to custom defaults.
  locales/en/messages.json
  src/css/main.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/protocols/stm32.js
  src/js/serial_backend.js
  src/main.html
Labels: RN: Improvement

#1656 Updated changelog for 10.6.0.
  changelog.html
Labels: documentation update

#1657 Added analytics for new configurator elements.
  locales/en/messages.json
  src/js/Analytics.js
  src/js/CliAutoComplete.js
  src/js/localization.js
  src/js/main.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/vtx.js
  src/tabs/vtx.html
  test/tabs/cli.js
Labels: RN: Improvement

#1663 Updated version for 10.6.0-RC1
  manifest.json
  package.json
Labels: Housekeeping

#1666 Fixed RPM build for release candidates.
  gulpfile.js
Labels: RN: Bugfix, fixes broken build

#1662 Tuning sliders yaw P fix
  src/js/TuningSliders.js
Labels: RN: Bugfix

#1665 Fix tooltip not closing properly
  src/js/gui.js
Labels: RN: Bugfix

#1672 Fix dark mode on ports tab select boxes
  src/css/tabs-dark/ports-dark.css
  src/css/tabs/ports.css
Labels: RN: Bugfix

#1678 Fix slider display update and analytics
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1686 Fix forced dark mode if dark mode on OS level
  locales/en/messages.json
  src/css/main.css
  src/js/DarkTheme.js
  src/js/main.js
  src/main.html
  src/tabs/options.html
Labels: RN: Bugfix

#1689 Fix esc protocol tooltip for removed dshot1200
  locales/en/messages.json
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: Bugfix

#1692 Added support for Unified Target configurations with manufacturer_id in the name.
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: Bugfix

#1696 Update translations
  locales/de/messages.json
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/pt/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
Labels: Translation

#1699 Updated version for 10.6.0-RC2
  manifest.json
  package.json
Labels: Housekeeping

#1695 FIx memory leak on model rendering
  src/js/model.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
  src/js/tabs/setup.js
Labels: RN: Bugfix

#1690 Fixed naming of the 'Altitude' graph in the sensors tab.
  locales/en/messages.json
  src/css/tabs/sensors.css
  src/js/tabs/sensors.js
  src/tabs/sensors.html
Labels: RN: Bugfix

#1693 Don't accept fancy lookin letters in Unified configs
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
Labels: RN: Bugfix

#1698 Fix led color picker
  src/css/tabs/led_strip.css
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: RN: Bugfix
