Repository betaflight/betaflight-configurator, pull requests merged in 2019-05, with the labels that each got.

#1408 Moved from 'npm' to 'yarn'.
  .travis.yml
  README.md
  gulpfile.js
  package-lock.json
  package.json
  yarn.lock
Labels: RN: Improvement

#1412 Updating node packages to latest version.
  package.json
  yarn.lock
Labels: RN: Improvement

#1413 Update OSD symbols
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#1411 Add Croatian translation
  assets/windows/installer.nsi
  locales/en/messages.json
  locales/hr/messages.json
  src/js/localization.js
Labels: RN: New Language

#1415 Fixed yarn install for production dependencies, fixed instructions for development.
  README.md
  gulpfile.js
Labels: RN: Bugfix

#1417 Fixed links in the privacy policy.
  src/tabs/privacy_policy.html
Labels: RN: Bugfix

#1416 Added new fonts to dropdown list, started using the new symbols.
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#1421 Added devDependency on 'yarn' to enable production build.
  package.json
  yarn.lock
Labels: RN: Improvement, fixes broken build

#1420 Added altitude symbol in OSD.
  src/js/tabs/osd.js
Labels: RN: Improvement

#1425 Fixed yarn production install.
  gulpfile.js
  package.json
  yarn.lock
Labels: RN: Bugfix

#1426 New crash flag in 4.1 jostles the disarm flags
  locales/en/messages.json
  src/js/tabs/setup.js
Labels: RN: New UI Element

#1429 Update ROLL, PITCH, GPS LAT and LON OSD symbols
  src/js/tabs/osd.js
Labels: RN: Improvement

#1431 Make fonts available for older versions
  locales/en/messages.json
  resources/osd/1/betaflight.mcm
  resources/osd/1/bold.mcm
  resources/osd/1/clarity.mcm
  resources/osd/1/default.mcm
  resources/osd/1/digital.mcm
  resources/osd/1/extra_large.mcm
  resources/osd/1/impact.mcm
  resources/osd/1/impact_mini.mcm
  resources/osd/1/large.mcm
  resources/osd/1/vision.mcm
  resources/osd/2/betaflight.mcm
  resources/osd/2/bold.mcm
  resources/osd/2/clarity.mcm
  resources/osd/2/default.mcm
  resources/osd/2/digital.mcm
  resources/osd/2/extra_large.mcm
  resources/osd/2/impact.mcm
  resources/osd/2/impact_mini.mcm
  resources/osd/2/large.mcm
  resources/osd/2/vision.mcm
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: Improvement

#1430 Add Home Flag symbol to Home Distance OSD element
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight

#1433 Fixed wording in 32 kHz gyro sampling discontinuation message.
  locales/en/messages.json
Labels: RN: Bugfix

#1435 Update OSD Note message, about preview look and older firmware
  locales/en/messages.json
Labels: RN: Improvement

#1436 CliAutoComplete refining `set`
  src/js/CliAutoComplete.js
Labels: RN: Improvement

#1437 Move flash progress to toolbar
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/firmware_flasher.css
  src/js/tabs/firmware_flasher.js
  src/js/tabs/osd.js
  src/tabs/firmware_flasher.html
Labels: RN: Bugfix

#1438 User friendly messages for #1431
  locales/en/messages.json
Labels: RN: Improvement

#1440 Fix RX MSP window size
  src/css/tabs/receiver_msp.css
  src/js/tabs/receiver_msp.js
  src/tabs/receiver_msp.html
Labels: RN: Bugfix

#1441 Ignore RSSI channel in AUTO modes tab
  src/js/tabs/auxiliary.js
Labels: RN: Improvement

#1443 Add tenths of a second OSD timer precision option
  src/js/tabs/osd.js
Labels: RN: Improvement

#1444 Change order flashing buttons
  src/tabs/firmware_flasher.html
Labels: RN: Bugfix

#1448 Update arming disabled flags names
  src/js/tabs/setup.js
Labels: RN: New UI Element

#1451 Reorder OSD elements priority
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1452 Add PID and RATE Profile Name to OSD preview
  src/js/tabs/osd.js
Labels: RN: New UI Element

#1450 Add a select font preview in OSD
  locales/en/messages.json
  src/css/tabs/osd.css
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: Improvement

#1453 Add OSD profile names OSD element
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1454 Add tooltips for PID and RATE profiles names OSD elements
  locales/en/messages.json
Labels: RN: Bugfix

#1457 Fix registering lasttab click more than once
  src/js/main.js
Labels: RN: Bugfix

#1459 Align altitude left in OSD
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1439 Add voltage and amperage scale calibration
  locales/en/messages.json
  src/css/main.css
  src/js/tabs/power.js
  src/tabs/power.html
Labels: RN: Improvement

#1465 Remove the OSD preview logo switch
  locales/en/messages.json
  src/css/tabs/osd.css
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: Improvement

#1466 Add speedometer and total distance icons to fonts
  resources/osd/2/betaflight.mcm
  resources/osd/2/bold.mcm
  resources/osd/2/clarity.mcm
  resources/osd/2/default.mcm
  resources/osd/2/digital.mcm
  resources/osd/2/extra_large.mcm
  resources/osd/2/impact.mcm
  resources/osd/2/impact_mini.mcm
  resources/osd/2/large.mcm
  resources/osd/2/vision.mcm
Labels: RN: Improvement

#1469 Fix button order in tabs
  src/css/main.css
  src/tabs/logging.html
  src/tabs/pid_tuning.html
  src/tabs/power.html
  src/tabs/receiver.html
Labels: RN: Bugfix
