Repository betaflight/betaflight-configurator, pull requests merged in 2019-01, with the labels that each got.

#1271 Check selected blackbox device before allowing mass storage reboot
  src/js/tabs/onboard_logging.js
Labels: Bugfix

#1278 Add support for 32bit OSD warnings bitmask; add missing warnings elements
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight

#1283 Add support for OSD Profile and LED Profile in-flight adjustments
  locales/en/messages.json
  src/js/tabs/adjustments.js
Labels: enhancement

#1285 Added OSD preview for stick overlays, added custom symbols for stick overlays to fonts.
  .gitignore
  locales/en/messages.json
  resources/osd/betaflight.mcm
  resources/osd/bold.mcm
  resources/osd/clarity.mcm
  resources/osd/default.mcm
  resources/osd/digital.mcm
  resources/osd/extra_large.mcm
  resources/osd/large.mcm
  resources/osd/vision.mcm
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight
