Repository betaflight/betaflight-configurator, pull requests merged in 2019-06, with the labels that each got.

#1467 Use the new Speed and Flight Distance OSD symbols
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1475 Remove second throttle symbol from OSD
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1479 Added I18n strings for RPMFILTER and REBOOT_REQD flags from #1448
  locales/en/messages.json
Labels: RN: New UI Element

#1480 Fix min limit of gps_rescue_min_sats to 5
  src/tabs/failsafe.html
Labels: RN: Bugfix

#1483 Removed adjustment range slots from the UI.
  locales/en/messages.json
  src/js/tabs/adjustments.js
  src/tabs/adjustments.html
Labels: RN: New UI Element

#1485 Order OSD elements in alphabetical order
  src/js/tabs/osd.js
Labels: RN: Improvement

#1487 i18n OSD Elements
  locales/en/messages.json
  src/js/localization.js
  src/js/tabs/osd.js
Labels: RN: Improvement

#1477 Refactor fonts
  resources/osd/1/impact.mcm
  resources/osd/1/impact_mini.mcm
  resources/osd/2/betaflight.mcm
  resources/osd/2/bold.mcm
  resources/osd/2/clarity.mcm
  resources/osd/2/default.mcm
  resources/osd/2/digital.mcm
  resources/osd/2/extra_large.mcm
  resources/osd/2/impact.mcm
  resources/osd/2/impact_mini.mcm
  resources/osd/2/large.mcm
  resources/osd/2/vision.mcm
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#1491 Add osd rssi dbm
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: New UI Element

#1488 Add vario units to the preview
  resources/osd/1/betaflight.mcm
  resources/osd/1/bold.mcm
  resources/osd/1/clarity.mcm
  resources/osd/1/default.mcm
  resources/osd/1/digital.mcm
  resources/osd/1/extra_large.mcm
  resources/osd/1/impact.mcm
  resources/osd/1/impact_mini.mcm
  resources/osd/1/large.mcm
  resources/osd/1/vision.mcm
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1493 remove extra Byte order mark from beginning of src/main.html
  src/main.html
Labels: RN: Bugfix

#1494 Fix missing OSD preview symbols
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1496 i18n some static options from the OSD
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement

#1497 i18n the OSD warnings list, ordering it in alphabetical order
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement

#1473 Add switchable dark mode
  libraries/jbox/jbox-dark.css
  locales/en/messages.json
  src/css/main-dark.css
  src/css/tabs-dark/adjustments-dark.css
  src/css/tabs-dark/auxiliary-dark.css
  src/css/tabs-dark/cli-dark.css
  src/css/tabs-dark/configuration-dark.css
  src/css/tabs-dark/failsafe-dark.css
  src/css/tabs-dark/firmware_flasher-dark.css
  src/css/tabs-dark/gps-dark.css
  src/css/tabs-dark/help-dark.css
  src/css/tabs-dark/landing-dark.css
  src/css/tabs-dark/led_strip-dark.css
  src/css/tabs-dark/logging-dark.css
  src/css/tabs-dark/motors-dark.css
  src/css/tabs-dark/onboard_logging-dark.css
  src/css/tabs-dark/osd-dark.css
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs-dark/ports-dark.css
  src/css/tabs-dark/power-dark.css
  src/css/tabs-dark/receiver-dark.css
  src/css/tabs-dark/receiver_msp-dark.css
  src/css/tabs-dark/sensors-dark.css
  src/css/tabs-dark/servos-dark.css
  src/css/tabs-dark/setup-dark.css
  src/css/tabs-dark/setup_osd-dark.css
  src/css/tabs-dark/transponder-dark.css
  src/css/tabs/pid_tuning.css
  src/images/paper-dark.jpg
  src/js/DarkTheme.js
  src/js/main.js
  src/main.html
  src/tabs/options.html
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1504 Add Km, Mi and LQ symbols to fonts
  resources/osd/2/betaflight.mcm
  resources/osd/2/bold.mcm
  resources/osd/2/clarity.mcm
  resources/osd/2/default.mcm
  resources/osd/2/digital.mcm
  resources/osd/2/extra_large.mcm
  resources/osd/2/impact.mcm
  resources/osd/2/impact_mini.mcm
  resources/osd/2/large.mcm
  resources/osd/2/vision.mcm
Labels: RN: Font update

#1505 Add Link Quality symbol to the OSD preview
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: New UI Element

#1506 Add minimum RSSI dBm OSD statistic
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: New UI Element

#1508 tweaks to dark theme
  src/css/main-dark.css
  src/css/main.css
  src/css/tabs-dark/adjustments-dark.css
  src/css/tabs-dark/auxiliary-dark.css
  src/css/tabs-dark/cli-dark.css
  src/css/tabs-dark/failsafe-dark.css
  src/css/tabs-dark/firmware_flasher-dark.css
  src/css/tabs-dark/motors-dark.css
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs/firmware_flasher.css
  src/css/tabs/osd.css
  src/css/tabs/pid_tuning.css
  src/images/icons/cf_failsafe_procedure1-dark.svg
  src/images/icons/cf_failsafe_procedure2-dark.svg
  src/images/icons/cf_failsafe_procedure4-dark.svg
  src/images/icons/cf_icon_info_white.svg
  src/js/gui.js
  src/js/tabs/pid_tuning.js
  src/tabs/configuration.html
  src/tabs/firmware_flasher.html
  src/tabs/osd.html
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1509 Updated the Chrome Web Store URL for the ChromeOS only version.
  README.md
Labels: Housekeeping

#1499 i18n final statistics from OSD
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement

#1507 Add unknown statistics fields to OSD
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement
