Repository betaflight/betaflight-configurator, pull requests merged in 2019-07, with the labels that each got.

#1511 Fix power tab
  src/js/tabs/power.js
Labels: RN: Bugfix

#1512 End i18n work of OSD statistics
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1514 Add Calibration Manager title to i18n
  locales/en/messages.json
  src/js/tabs/power.js
Labels: RN: Bugfix

#1515 Fix mouse scroll in CLI load from file
  src/js/tabs/cli.js
Labels: RN: Bugfix

#1517 Fix OSD Home Distance preview
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1516 Add images to the MCM fonts
  gulpfile.js
  resources/osd/1/betaflight.png
  resources/osd/1/bold.png
  resources/osd/1/clarity.png
  resources/osd/1/default.png
  resources/osd/1/digital.png
  resources/osd/1/extra_large.png
  resources/osd/1/impact.png
  resources/osd/1/impact_mini.png
  resources/osd/1/large.png
  resources/osd/1/vision.png
  resources/osd/2/betaflight.png
  resources/osd/2/bold.png
  resources/osd/2/clarity.png
  resources/osd/2/default.png
  resources/osd/2/digital.png
  resources/osd/2/extra_large.png
  resources/osd/2/impact.png
  resources/osd/2/impact_mini.png
  resources/osd/2/large.png
  resources/osd/2/vision.png
Labels: RN: Improvement

#1521 Adding a hint to SERVO_TILT feature to mention CAMSTAB mode
  locales/en/messages.json
  src/js/Features.js
Labels: RN: Improvement

#1520 Fix and make bigger max size local file to flash
  src/js/tabs/firmware_flasher.js
Labels: RN: Bugfix

#1523 Refactor flashing progress bar code
  src/js/protocols/stm32.js
  src/js/protocols/stm32usbdfu.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#1526 Changed the description of the initialSetupArmingDisableFlagsTooltip...
  locales/en/messages.json
Labels: Housekeeping

#1522 add a default handler for serial errors (disconnect)
  locales/en/messages.json
  src/js/serial.js
Labels: RN: Improvement

#1528 Force trim multi-bank option byte descriptor to the first one
  src/js/protocols/stm32usbdfu.js
Labels: RN: Improvement

#1530 Move the localization badge upwards
  README.md
Labels: documentation update

#1531 tidy up .gitignore
  .gitignore
Labels: Housekeeping

#1534 Fix opening of external links in browser.
  src/js/main.js
Labels: RN: Bugfix

#1536 avoid highlighting items in the Post Flight Statistics
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1537 Lets count those LEDs properly
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#1540 Fix storage key name for caching the jenkins builds list.
  src/js/jenkins_loader.js
Labels: RN: Bugfix

#1542 Fix errors in failsafe parameter ranges
  src/tabs/failsafe.html
Labels: RN: Bugfix

#1235 Updated VTX settings OSD preview for status indicator.
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight

#1544 fix gulp tasks such that yarn gets its lock file
  .travis.yml
  gulpfile.js
Labels: build system improvement
