Repository betaflight/betaflight-configurator, pull requests merged in 2019-08, with the labels that each got.

#1545 patreon link shouldn't open in the main window
  locales/en/messages.json
Labels: RN: Improvement

#1549 Refactored some CSS to use vars
  src/css/main.css
  src/css/tabs/adjustments.css
  src/css/tabs/auxiliary.css
  src/css/tabs/help.css
  src/css/tabs/landing.css
  src/css/tabs/led_strip.css
  src/css/tabs/motors.css
  src/css/tabs/onboard_logging.css
  src/css/tabs/pid_tuning.css
  src/css/tabs/receiver_msp.css
Labels: RN: Improvement

#1550 add an alternative to chrome.storage.local
  src/js/ConfigStorage.js
  src/js/gui.js
  src/js/localization.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/auxiliary.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/main.html
Labels: RN: Improvement

#1552 CliAutocomplete fix mouse activation #1481
  src/css/tabs-dark/cli-dark.css
  src/css/tabs/cli.css
  src/js/CliAutoComplete.js
Labels: RN: Bugfix

#1547 tweak tab placement on the landing page
  changelog.html
  gulpfile.js
  src/css/main.css
  src/css/tabs/landing.css
  src/css/tabs/static_tab.css
  src/js/gui.js
  src/js/main.js
  src/js/tabs/landing.js
  src/js/tabs/static_tab.js
  src/main.html
  src/tabs/landing.html
Labels: RN: Improvement

#1553 Updated changelog for 10.5.1.
  changelog.html
Labels: Housekeeping

#1554 Improved formatting for the privacy policy.
  src/css/tabs/privacy_policy.css
  src/main.html
  src/tabs/privacy_policy.html
Labels: RN: Improvement

#1556 Add powerlabel to the VTX OSD preview element
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#1558 Updated versions of vulnerable packages.
  yarn.lock
Labels: RN: Improvement

#1559 Added Spektrum SRXL2 to serialRXtypes
  src/js/tabs/configuration.js
Labels: RN: New UI Element

#1561 Fix ordering locale with underscore
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1560 Chrome Apps don't get window.localStorage
  src/js/ConfigStorage.js
  src/js/gui.js
  src/js/main.js
Labels: RN: Bugfix

#1564 Add iterm relax cutoff to UI
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: New UI Element

#1555 switch languages without an app restart
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/landing.css
  src/js/localization.js
  src/js/main.js
  src/js/port_handler.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/landing.js
  src/main.html
  src/tabs/landing.html
  src/tabs/options.html
Labels: RN: Improvement

#1568 fix a deprecation in jQuery 3.0 (Firmware flasher tab)
  src/js/jenkins_loader.js
Labels: RN: Bugfix

#1570 reorder a read of a configuration on receiver tab
  src/js/tabs/receiver.js
Labels: RN: Bugfix

#1571 Make the 'Update Firmware' buttom more consistent
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#1565 Initial support for flashing EXST .hex files to External Flash.
  locales/en/messages.json
  src/js/protocols/stm32usbdfu.js
  src/js/workers/hex_parser.js
Labels: RN: Improvement

#1567 Add dynamic notch settings to UI
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1573 read version information from... version.json
  gulpfile.js
  src/js/backup_restore.js
  src/js/main.js
Labels: RN: Improvement

#1574 Fixed dependency vulnerabilities.
  package.json
  yarn.lock
Labels: RN: Bugfix

#1566 Add debug modes to blackbox tab
  locales/en/messages.json
  src/css/tabs-dark/onboard_logging-dark.css
  src/css/tabs/onboard_logging.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/onboard_logging.js
  src/tabs/onboard_logging.html
Labels: Needs coordination with betaflight, RN: New UI Element

#1575 Simplified configuration of fast SBus.
  src/js/tabs/configuration.js
Labels: Needs coordination with betaflight, RN: Improvement

#1576 Add a way to avoid trying to add a custom icon when building nw.js
  assets/windows/installer.nsi
  gulpfile.js
Labels: build system improvement

#1578 get rid of superfluous notification
  src/js/eventPage.js
Labels: RN: Improvement

#1577 Add FF2.0 debug modes
  src/js/tabs/onboard_logging.js
Labels: RN: New UI Element

#1579 Fix iterm cutoff showing when iterm relax disabled
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1580 Add support for custom gyro alignment.
  src/js/tabs/configuration.js
Labels: RN: New UI Element

#1581 pretty up the windows installer
  assets/windows/bf_installer.bmp
  assets/windows/installer.nsi
Labels: RN: Improvement

#1583 Small bug fixes
  src/js/ConfigStorage.js
  src/js/FirmwareCache.js
  src/js/jenkins_loader.js
Labels: RN: Bugfix

#1569 Add an VTX tab
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/vtx.css
  src/js/fc.js
  src/js/gui.js
  src/js/main.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/setup_osd.js
  src/js/tabs/vtx.js
  src/main.html
  src/tabs/vtx.html
Labels: Needs coordination with betaflight, RN: Improvement

#1585 Added flashing of Unified Targets from configurations.
  src/js/ConfigInserter.js
  src/js/tabs/firmware_flasher.js
  src/main.html
Labels: RN: Improvement

#1589 Added requirement for node version 10.
  README.md
  package.json
Labels: build system improvement

#1590 Added .nvmrc file to enable automatic node version selection with 'nvm'.
  .nvmrc
Labels: build system improvement

#1591 Ignore the l10n_master branch for CI purposes
  .travis.yml
Labels: build system improvement

#1582 Replace legacy firmware reboot sequence with MSP based sequence.
  locales/en/messages.json
  src/js/msp/MSPConnector.js
  src/js/protocols/stm32.js
  src/main.html
Labels: RN: Improvement, rebase / squash required

#1595 reorder config requests on sensors tab
  src/js/tabs/sensors.js
Labels: RN: Bugfix

#1584 Improve PID Tuning tab style and layout
  locales/en/messages.json
  src/css/tabs-dark/pid_tuning-dark.css
  src/css/tabs/pid_tuning.css
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1600 Fixed structure of VTX tab Introduction string
  locales/en/messages.json
Labels: RN: Improvement

#1599 Add rc smoothing auto smoothness to UI, fix refresh button and slowdown
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: Improvement

#1602 Add telemetry dshot data info to the motors tab
  locales/en/messages.json
  src/css/tabs/motors.css
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
  src/tabs/motors.html
Labels: Needs coordination with betaflight, RN: New UI Element

#1604 Change the tooltip attach method
  src/js/gui.js
Labels: RN: Bugfix
