Repository betaflight/betaflight-configurator, pull requests merged in 2020-04, with the labels that each got.

#1943 Added version information to Unified Targets when they are flashed.
  locales/en/messages.json
  src/js/GitHubApi.js
  src/js/release_checker.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/osd.js
  src/main.html
  src/tabs/firmware_flasher.html
Labels: RN: Improvement

#1949 Fix D values when Dmin disabled and autoadjust, coordination with new Dmin values
  src/js/TuningSliders.js
  src/js/tabs/pid_tuning.js
Labels: Needs coordination with betaflight, RN: Improvement

#1950 Updated ItermCutoff and Dynamic Idle tooltips
  locales/en/messages.json
Labels: RN: Improvement

#1933 Added support for disabling the motor output protocol.
  locales/en/messages.json
  src/js/Features.js
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/configuration.js
  src/js/tabs/setup.js
  src/main.html
  src/tabs/configuration.html
Labels: Needs coordination with betaflight, RN: Improvement

#1951 Improved version PID defaults Sliders reading
  src/js/TuningSliders.js
  src/js/fc.js
Labels: RN: Improvement

#1953 Fixed naming of ANGLE mode in OSD preview.
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1952 Renamed Derivative to DMax when using Dmin
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1957 Fixed the styling of the landing page.
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/landing.css
  src/tabs/landing.html
Labels: RN: Improvement

#1956 Added warning when connecting to firmware newer than configurator.
  locales/en/messages.json
  src/css/dark-theme.css
  src/css/main.css
  src/js/RateCurve.js
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
  src/js/tabs/setup.js
Labels: RN: Improvement

#1959 Added analytics data collection for the PID loop frequency.
  src/js/tabs/configuration.js
Labels: RN: Improvement

#1970 Update yaw P in configurator to 45
  src/js/fc.js
Labels: RN: Improvement

#1932 LogoManager SonarLint fixes
  src/js/LogoManager.js
Labels: RN: Improvement

#1968 Fix OSD tab save button behavior
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1966 Yaw Response slider to work like pitch and roll
  src/js/TuningSliders.js
Labels: RN: Improvement

#1973 Updated link for new translators to point to the instructions in the Betaflight README.
  README.md
  locales/en/messages.json
Labels: Needs coordination with betaflight, documentation update

#1963 Fix the landing page - again. And fix the tabs broken in the last fix.
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/landing.css
Labels: RN: Bugfix

#1962 update Bidirectional DShot messages
  locales/en/messages.json
Labels: RN: Improvement

#1960 Fix style width for large target names
  src/css/main.css
Labels: RN: Bugfix

#1969 PD Balance Slider now adjusts D, fixes yaw P issue, tooltip update
  locales/en/messages.json
  src/js/TuningSliders.js
Labels: RN: Improvement

#1971 Fixed pull request template.
  .github/pull_request_template.md
Labels: documentation update

#1977 Fix Motor Limit Tooltip Examples
  locales/en/messages.json
Labels: RN: Improvement

#1979 Fixed closing of the problems dialog
  src/js/serial_backend.js
Labels: RN: Bugfix

#1976 Improve pidTuningIdleMinRpmHelp Tooltip text
  locales/en/messages.json
Labels: RN: Improvement

#1981 Fixed closing of the custom defaults dialog
  src/js/serial_backend.js
Labels: RN: Bugfix

#1987 Add Hungarian translation
  assets/windows/installer.nsi
  locales/en/messages.json
  locales/hu/messages.json
  src/js/localization.js
Labels: RN: New Language

#1988 Add Traditional Chinese translation
  assets/windows/installer.nsi
  locales/en/messages.json
  locales/zh_TW/messages.json
  src/js/localization.js
Labels: RN: New Language

#1967 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
Labels: RN: Improvement

#1982 Fixed opening of links in an external app.
  manifest.json
  package.json
  src/js/chromeAppEventPage.js
  src/js/eventPage.js
  src/js/main.js
  src/main_nwjs.html
Labels: RN: Bugfix

#1984 Fixed units shown for dynamic idle.
  locales/en/messages.json
Labels: RN: Bugfix

#1985 Added entry for 10.7.0 to changelog.
  changelog.html
Labels: Housekeeping

#1983 Fixed Rc Auto Smoothness max 50
  src/js/tabs/receiver.js
Labels: RN: Bugfix

#1986 Updated version to 10.7.0-RC1
  manifest.json
  package.json
Labels: Housekeeping
