Repository betaflight/betaflight-configurator, pull requests merged in 2020-06, with the labels that each got.

#2042 Fixed the antigravity feature switch.
  locales/en/messages.json
  src/js/Features.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: Bugfix

#2043 Added injection of custom defaults header when flashing local file.
  src/js/tabs/firmware_flasher.js
Labels: Needs coordination with betaflight, RN: Improvement

#2044 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/hu/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: Translation

#2045 Updated version to 10.6.0-RC2
  manifest.json
  package.json
Labels: Housekeeping

#2048 Fixed auto_profile_cellcount negative value reads
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#2050 Fixed reporting of PID loop settings.
  src/js/tabs/configuration.js
Labels: RN: Bugfix

#2054 Update translations
  locales/eu/messages.json
  locales/fr/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/pt_BR/messages.json
Labels: Translation

#2053 Fixed PID tuning sliders disabling on certain values.
  src/js/TuningSliders.js
Labels: RN: Bugfix

#2056 Updated version to 10.7.0.
  manifest.json
  package.json
Labels: Housekeeping

#2059 Updated version to 10.8.0, updated supported API version to 1.44.
  manifest.json
  package.json
  src/js/data_storage.js
Labels: Housekeeping

#2012 DarkTheme auto change when prefers color scheme change
  src/js/DarkTheme.js
  src/js/main.js
Labels: RN: Improvement

#2068 Added Dynamic Lpf Dterm Curve Expo to UI
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: Improvement

#1992 Fixing Rc Smoothing Settings
  src/js/tabs/receiver.js
Labels: RN: Bugfix

#1878 FF Interpolate Options
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: Improvement

#2015 Hide GPS elements if not selected AUTO
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: Improvement

#2074 Updated NW.js to 44.6.
  gulpfile.js
Labels: RN: Improvement

#2091 Move three.js library to npm library and upgrade to version 0.110.0
  libraries/three/CanvasRenderer.js
  libraries/three/Projector.js
  libraries/three/three.min.js
  package.json
  src/js/model.js
  src/main.html
  yarn.lock
Labels: RN: Improvement

#2078 Change self-closing <div>, <span> and <p> tags
  src/js/tabs/osd.js
  src/js/tabs/setup.js
  src/tabs/configuration.html
  src/tabs/firmware_flasher.html
  src/tabs/pid_tuning.html
  src/tabs/vtx.html
Labels: RN: Bugfix
