Repository betaflight/betaflight-configurator, pull requests merged in 2020-12, with the labels that each got.

#2298 Remove colorAmbient from THREE.js as it's no longer supported
  resources/models/fallback.json
  resources/models/hex_plus.json
  resources/models/hex_x.json
  resources/models/quad_atail.json
  resources/models/quad_vtail.json
  resources/models/quad_x.json
  resources/models/tricopter.json
  resources/models/y4.json
  resources/models/y6.json
Labels: RN: Bugfix

#2266 Fix Hardware Id hiding when no version detected
  src/js/port_handler.js
Labels: RN: Bugfix

#2323 Change lexical scope configInsert and configStorage
  src/js/ConfigInserter.js
  src/js/ConfigStorage.js
Labels: RN: Improvement

#2328 Disable Exit Dfu Mode and Load Firmware buttons while flashing
  src/js/tabs/firmware_flasher.js
Labels: RN: Bugfix

#2332 Fix drawStickOverlayPreview in OSD
  src/js/tabs/osd.js
Labels: RN: Improvement

#2306 Change lexical scope workers
  src/js/workers/hex_parser.js
Labels: RN: Improvement

#2335 Improving hardwareId behavior
  src/components/betaflight-logo/BetaflightLogo.vue
  src/js/port_handler.js
Labels: RN: Improvement

#2312 Change lexical scope transponder
  src/js/tabs/transponder.js
Labels: RN: Improvement

#2314 Change lexical scope logging and help
  src/js/tabs/help.js
  src/js/tabs/logging.js
  src/js/tabs/onboard_logging.js
Labels: RN: Improvement

#2310 Change lexical scope tuning
  src/js/TuningSliders.js
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#2313 Change lexical scope receiver and failsafe
  src/js/tabs/failsafe.js
  src/js/tabs/receiver.js
  src/js/tabs/receiver_msp.js
Labels: RN: Improvement

#2333 Fix Load Firmware buttons reactivation after flash
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#2307 Change lexical scope utils
  src/js/utils/window_watchers.js
Labels: RN: Improvement

#2311 Change lexical scope motors, sensors, configuration
  src/js/tabs/configuration.js
  src/js/tabs/motors.js
  src/js/tabs/sensors.js
Labels: RN: Improvement

#2342 Add flex to Android logo_text
  src/components/betaflight-logo/BetaflightLogo.vue
Labels: RN: Bugfix

#2308 Change lexical scope msp
  src/js/msp.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPConnector.js
  src/js/msp/MSPHelper.js
Labels: RN: Improvement

#2334 Enabled pull request validation in azure.
  azure-pipelines.yml
Labels: build system improvement

#2315 Change lexical scope osd
  src/js/tabs/landing.js
  src/js/tabs/map.js
  src/js/tabs/setup_osd.js
  src/js/tabs/static_tab.js
Labels: RN: Improvement

#2316 Change lexical scope adjustments
  src/js/tabs/adjustments.js
Labels: RN: Improvement

#2317 Change lexical scope auxiliary
  src/js/tabs/auxiliary.js
Labels: RN: Improvement

#2318 Change lexical scope gps
  src/js/tabs/gps.js
Labels: RN: Improvement

#2352 Fix and consolidate check for chrome.runtime.lastError
  src/js/LogoManager.js
  src/js/backup_restore.js
  src/js/main.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/logging.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/vtx.js
  src/js/utils/common.js
  src/main.html
Labels: RN: Bugfix

#2345 Added grid feature to osd preview
  src/css/dark-theme.css
  src/css/tabs/osd.css
  src/images/osd-bg-1-grid.png
Labels: RN: Improvement

#2336 Fixed broken link in README.md.
  README.md
Labels: documentation update

#2337 Added translation comment to 'missing information' bot.
  .github/no-response.yml
Labels: build system improvement

#2343 Fix out of bounds error in pid_tuning
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#2354 Added automated builds for maintenance branches.
  azure-pipelines.yml
Labels: build system improvement

#2353 Fix markers on aux tab
  src/js/tabs/auxiliary.js
Labels: RN: Bugfix

#2351 Fixed non working quad-status-wrapper
  src/js/serial_backend.js
Labels: RN: Bugfix

#2348 bump nw.js to version 0.50.2
  gulpfile.js
Labels: RN: Improvement

#2189 Add eslint with pre-commit hook
  .eslintrc.js
  .gitignore
  .travis.yml
  package.json
  src/components/init.js
  src/components/quad-status/BatteryLegend.vue
  src/components/status-bar/PortUtilization.vue
  src/components/status-bar/StatusBar.vue
  src/js/FirmwareCache.js
  src/js/TuningSliders.js
  src/js/huffman.js
  src/js/injected_methods.js
  src/js/msp.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPConnector.js
  src/js/msp/MSPHelper.js
  src/js/peripherals.js
  src/js/protocols/stm32usbdfu.js
  src/js/release_checker.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/help.js
  src/js/tabs/map.js
  src/js/tabs/motors.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/setup_osd.js
  yarn.lock
Labels: build system improvement

#2321 Change lexical scope power
  src/js/tabs/power.js
Labels: RN: Improvement

#2325 Change lexical scope jenkins
  src/js/jenkins_loader.js
Labels: RN: Improvement

#2326 Change lexical scope ratecurve
  src/js/RateCurve.js
Labels: RN: Improvement

#2329 Change lexical Scope setup tab
  src/js/tabs/setup.js
Labels: RN: Improvement

#2283 Added Virtual Mode (Virtual Fc Part 1 & 2)
  locales/en/messages.json
  src/css/main.css
  src/js/VirtualFC.js
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/main.js
  src/js/msp.js
  src/js/port_handler.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/tabs/gps.js
  src/js/tabs/osd.js
  src/js/tabs/setup.js
  src/js/utils/common.js
  src/main.html
Labels: RN: Feature

#2322 Change lexical scope backup_restore
  src/js/backup_restore.js
Labels: RN: Improvement

#2327 Change lexical scope remaining root files
  src/js/Analytics.js
  src/js/Clipboard.js
  src/js/DarkTheme.js
  src/js/boards.js
  src/js/data_storage.js
  src/js/default_huffman_tree.js
  src/js/huffman.js
  src/js/model.js
  src/js/peripherals.js
  src/js/release_checker.js
Labels: RN: Improvement

#2324 Change lexical scope Features
  src/js/Features.js
Labels: RN: Improvement

#2357 Added linter run to tests.
  .travis.yml
  package.json
Labels: build system improvement

#2363 Fix null when CLI autocomplete resource
  src/js/CliAutoComplete.js
Labels: RN: Bugfix
