Repository betaflight/betaflight-configurator, pull requests merged in 2020-10, with the labels that each got.

#2188 Fix Sonar issues in gui.js
  src/js/Clipboard.js
  src/js/gui.js
  src/js/tabs/vtx.js
Labels: RN: Improvement

#2195 Fixed receiver and motor tabs plot style
  src/css/tabs/motors.css
  src/css/tabs/receiver.css
Labels: RN: Improvement

#2194 Fixed rate modes background color for Darktheme
  src/css/dark-theme.css
Labels: RN: Improvement

#2192 Fix Sonar issues from osd.js
  src/js/tabs/osd.js
Labels: RN: Refactoring

#2187 Refactor and Sonar clean of Beeper.js
  src/js/Beepers.js
  src/js/backup_restore.js
  src/js/msp/MSPHelper.js
Labels: RN: Improvement

#2179 Unlock DFU using boot button after #2169
  src/js/port_handler.js
Labels: RN: Bugfix

#2190 Update FF Interpolate default
  src/js/tabs/pid_tuning.js
Labels: Needs coordination with betaflight, RN: Improvement

#2186 Remove ChromeOS support
  .travis.yml
  README.md
  gulpfile.js
  manifest.json
  src/js/Clipboard.js
  src/js/ConfigStorage.js
  src/js/chromeAppEventPage.js
  src/js/gui.js
  src/js/main.js
  src/js/tabs/vtx.js
Labels: RN: Improvement

#2197 Add degrees to accelerometer for X and Y axis in sensor tab
  locales/en/messages.json
  src/js/tabs/sensors.js
Labels: RN: Improvement

#2208 Add feedforward to OSD PID element preview
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#2213 Add release and license badge to README
  README.md
Labels: documentation update

#2215 Added darkmode and cordova compatibility to receiver tab rx plot
  src/css/dark-theme.css
  src/css/tabs/receiver.css
Labels: Android, RN: Improvement

#2218 Add Thrust Linearization
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: Improvement

#2217 Fix OSD upload font
  src/js/tabs/osd.js
Labels: RN: Bugfix

#2182 Add Vue js into the codebase
  gulpfile.js
  locales/en/messages.json
  package.json
  src/components/MotorOutputReordering/Body.html
  src/components/MotorOutputReordering/MotorOutputReorderingCanvas.js
  src/components/MotorOutputReordering/MotorOutputReorderingComponent.js
  src/components/MotorOutputReordering/MotorOutputReorderingConfig.js
  src/components/MotorOutputReordering/Styles.css
  src/components/betaflight-logo/BetaflightLogo.vue
  src/components/init.js
  src/components/quad-status/BatteryLegend.vue
  src/components/status-bar/PortUtilization.vue
  src/components/status-bar/ReadingStat.vue
  src/components/status-bar/StatusBar.vue
  src/components/status-bar/StatusBarVersion.vue
  src/components/vueI18n.js
  src/css/dark-theme.css
  src/css/main.css
  src/js/fc.js
  src/js/localization.js
  src/js/main.js
  src/js/msp/MSPConnector.js
  src/js/msp/MSPHelper.js
  src/js/port_usage.js
  src/js/serial_backend.js
  src/main.html
  yarn.lock
Labels: RN: Feature

#2228 Fix some Sonar issue of gulpfile
  gulpfile.js
Labels: build system improvement

#2226 Fix npm scripts on Windows
  package.json
  yarn.lock
Labels: RN: Bugfix

#2225 Replace API versions by constants
  src/js/Beepers.js
  src/js/Features.js
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/protocols/stm32.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/setup.js
  src/js/tabs/vtx.js
Labels: RN: Refactoring

#2227 Add Vue devtools to the debug mode
  package.json
  src/components/init.js
  yarn.lock
Labels: RN: Improvement

#2230 Upgrade i18next backend to i18nextHttpBackend
  package.json
  src/js/localization.js
  src/main.html
  yarn.lock
Labels: RN: Improvement

#2232 Fix landing tab facebook logo
  src/css/tabs/landing.css
  src/tabs/landing.html
Labels: RN: Bugfix

#2233 Fix tuning sliders
  src/js/TuningSliders.js
Labels: RN: Bugfix

#2231 Fix Sonar issues Cli and CliAutoComplete
  package.json
  src/js/CliAutoComplete.js
  src/js/tabs/cli.js
  test/karma.conf.js
  test/tabs/cli.js
  yarn.lock
Labels: RN: Refactoring

#2234 Fix cpuload value status update after disconnect
  src/js/fc.js
Labels: RN: Bugfix

#2235 Added missing configurations for motor reordering (Octo X8, Octo Flat +, Octo Flat X, Bicopter, V-tail Quad, A-tail Quad, Y4, Y6)
  src/components/MotorOutputReordering/MotorOutputReorderingCanvas.js
  src/components/MotorOutputReordering/MotorOutputReorderingConfig.js
Labels: RN: Improvement

#2236 Remove window title hack for Chrome
  locales/en/messages.json
  package.json
  src/main.html
Labels: RN: Improvement

#2242 Move Switchery library to npm/yarn
  libraries/switchery/switchery.css
  libraries/switchery/switchery.js
  package.json
  src/css/switchery_custom.css
  src/js/gui.js
  src/main.html
  yarn.lock
Labels: RN: Improvement

#2237 Parse messages file and use i18next vue plugin
  locales/en/messages.json
  package.json
  src/components/betaflight-logo/BetaflightLogo.vue
  src/components/init.js
  src/components/status-bar/PortUtilization.vue
  src/components/status-bar/ReadingStat.vue
  src/components/status-bar/StatusBarVersion.vue
  src/components/vueI18n.js
  src/js/localization.js
  yarn.lock
Labels: RN: Improvement

#2238 Remove Q library
  libraries/q.js
  src/main.html
Labels: RN: Refactoring

#2241 Move Android to its own VM in the Azure pipeline
  azure-pipelines.yml
Labels: build system improvement

#2239 Change save to flash message and remove duplicate
  locales/en/messages.json
  src/tabs/onboard_logging.html
Labels: RN: Improvement

#2245 Replace i18next http backend by filesystem sync backend
  package.json
  src/js/localization.js
  src/main.html
  src/main_cordova.html
  yarn.lock
Labels: RN: Improvement

#2248 Update run-script-os to 1.1.3
  package.json
  yarn.lock
Labels: RN: Bugfix

#2249 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/hu/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: Translation

#2250 Delete old installation of Configurator before installing
  assets/windows/installer.iss
Labels: RN: Improvement

#2251 Remove underscore from _locales
  gulpfile.js
  package.json
  src/js/localization.js
Labels: RN: Improvement

#2256 Updated dependencies to fix error message when starting in debug mode.
  yarn.lock
Labels: RN: Bugfix

#2260 Restrict Windows version to Windows 8 or higher
  README.md
  assets/windows/installer.iss
Labels: Needs entry in release notes, RN: Improvement, documentation update

#2262 Fix require modules with Cordova
  gulpfile.js
  package.json
  yarn.lock
Labels: Android, RN: Improvement

#2261 Replace timeout/interval functions by Node ones
  src/js/main.js
Labels: RN: Improvement

#2264 Revert i18n fs backend
  package.json
  src/components/init.js
  src/js/localization.js
  src/main.html
  src/main_cordova.html
  yarn.lock
Labels: RN: Improvement
