Repository betaflight/betaflight-configurator, pull requests merged in 2020-08, with the labels that each got.

#2144 Added warnings about the limitations of power / amperage meter displays.
  locales/en/messages.json
  src/tabs/power.html
Labels: RN: Improvement

#2093 Motor output reordering feature (Configurator part)
  locales/en/messages.json
  src/Components/MotorOutputReordering/Body.html
  src/Components/MotorOutputReordering/MotorOutputReorderingCanvas.js
  src/Components/MotorOutputReordering/MotorOutputReorderingComponent.js
  src/Components/MotorOutputReordering/MotorOutputReorderingConfig.js
  src/Components/MotorOutputReordering/Styles.css
  src/css/tabs/motors.css
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
  src/main.html
  src/tabs/motors.html
Labels: RN: Improvement

#2158 Azure-pipelines android build
  azure-pipelines.yml
Labels: build system improvement

#2146 Add support for British units in OSD
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#2160 New board select2 default cursor and arrow fix
  src/css/select2_custom.css
Labels: RN: Improvement

#2164 Add debug modes BLACKBOX_OUTPUT, GYRO_SAMPLE, RX_TIMING, D_LPF, VTX_TRAM
  src/js/tabs/onboard_logging.js
Labels: RN: Improvement

#2162 Refactor porthandler and add port description to the list
  src/css/dropdown-lists/css/style_lists.css
  src/js/port_handler.js
  src/js/serial.js
Labels: RN: Improvement

#2163 Add search and order to the blackbox debug modes list
  src/js/tabs/onboard_logging.js
Labels: RN: Improvement

#2165 Fixed auto dark theme on android
  cordova/package_template.json
  cordova/yarn.lock
  src/js/DarkTheme.js
  src/js/main.js
Labels: RN: Bugfix
