Repository betaflight/betaflight-configurator, pull requests merged in 2020-02, with the labels that each got.

#1868 Work with gyro native sampling
  locales/en/messages.json
  src/css/tabs/configuration.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/js/tabs/onboard_logging.js
  src/tabs/configuration.html
Labels: Needs coordination with betaflight, RN: Improvement

#1870 Remove 32k notice
  locales/en/messages.json
  src/js/tabs/configuration.js
Labels: RN: Improvement

#1869 Coordination with new Dynamic Notch improvements
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1875 Fix throttle preview refresh
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1874 Moved MacOS azure build to 10.15 because 10.13 has been deprecated.
  azure-pipelines.yml
Labels: build system improvement

#1873 Added bind button for receivers that support it.
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: Needs coordination with betaflight, RN: Improvement

#1879 Add OSD Camera Frame element
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement

#1880 Add support for the 'mah capacity exceeded' osd warning
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement

#1882 Fixed loop speed dropdowns for firmware versions with 32kHz gyro support.
  src/js/tabs/configuration.js
Labels: RN: Bugfix

#1885 Fix lua powerTable
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#1886 Fix long texts problem in auxiliary tab
  src/css/tabs/auxiliary.css
Labels: RN: Bugfix

#1889 Add Polish translation
  assets/windows/installer.nsi
  locales/en/messages.json
  locales/pl/messages.json
  src/js/localization.js
Labels: RN: New Language

#1883 Iterm Relax Cutoff Update
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1887 Hide the 'factory band' VTX table setting for VTX types that do not support it.
  locales/en/messages.json
  src/js/tabs/vtx.js
  src/tabs/vtx.html
Labels: RN: Improvement

#1894 Hide Accel Features when it is disabled
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: Improvement

#1893 Updated all dependencies and fixed resulting problem.
  gulpfile.js
  package.json
  src/js/main.js
  yarn.lock
Labels: RN: Improvement

#1898 Fixed cache expiry for Unified Target configurations.
  src/js/tabs/firmware_flasher.js
Labels: RN: Bugfix

#1895 Fixed exception thrown when clicking 'Connect' directly after application start.
  src/js/serial_backend.js
Labels: RN: Bugfix

#1896 Hide Esc Sensor for non digital protocols
  src/css/tabs/configuration.css
  src/js/Features.js
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: Improvement

#1891 High rates warning message to prevent desyncs
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement
