Repository betaflight/betaflight-configurator, pull requests merged in 2020-11, with the labels that each got.

#2255 chore: ESM for localization
  gulpfile.js
  package.json
  src/components/init.js
  src/components/vueI18n.js
  src/js/localization.js
  src/js/main_cordova.js
  src/main.html
  src/main_cordova.html
  test/karma.conf.js
  yarn.lock
Labels: RN: Improvement

#2272 Minor bugfixes MSPHelper.js
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#2263 Fix tcp boot issue
  src/js/cordova_chromeapi.js
  src/js/main.js
  src/js/port_handler.js
  src/js/serial.js
  src/js/serial_backend.js
Labels: RN: Improvement

#2276 chore: remove custom string formatting
  src/js/gui.js
  src/js/injected_methods.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#2280 fix unknown msp code 33 & 225 detected
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#2285 Remove unused mspHelper
  src/js/serial_backend.js
Labels: RN: Improvement

#2284 Moved getSerialRxTypes to not interfere with backup/restore
  src/js/fc.js
  src/js/tabs/configuration.js
  src/js/tabs/osd.js
Labels: RN: Improvement

#2282 THREE.MeshFaceMaterial has been removed. Use an Array instead.
  src/js/model.js
Labels: RN: Improvement

#2286 Added warning about translation pull requests.
  README.md
Labels: documentation update

#2287 Fix minor issues
  src/js/msp.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
Labels: RN: Bugfix

#2288 Added note discouraging the use of cross-platform builds.
  README.md
  gulpfile.js
Labels: build system improvement, documentation update

#2289 Fix Copy to Clipboard Button
  src/js/tabs/cli.js
Labels: RN: Bugfix

#2292 Make tab_container scrollable when it is needed
  src/css/main.css
Labels: RN: Improvement

#2295 Removed deprecated option from gulpfile.
  gulpfile.js
Labels: RN: Improvement

#2297 Cosmetic fix in gulpfile.
  gulpfile.js
Labels: RN: Improvement
