Repository betaflight/betaflight-configurator, pull requests merged in 2020-07, with the labels that each got.

#2087 vtx tab fix for device without vtx tables
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#2098 Fix vtxPower_X parameter string
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#2080 Update i18next to latest minor version of 19.0.0
  package.json
  yarn.lock
Labels: RN: Improvement

#2088 Update OpenLayers library to version 5.3.3
  libraries/openlayers/ol.css.map
  libraries/openlayers/ol.js
  libraries/openlayers/ol.js.map
Labels: RN: Improvement

#2097 Blackbox sample rate selection
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/onboard_logging.js
Labels: RN: Improvement

#2103 Added Vbat Sag Compensation to UI
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#2102 Replace NSIS by Inno Setup installer
  assets/windows/UnInst.nsh
  assets/windows/bf_installer_small.bmp
  assets/windows/bf_uninstaller_icon.ico
  assets/windows/installer.iss
  assets/windows/installer.nsi
  assets/windows/unofficial_inno_languages/Basque.isl
  assets/windows/unofficial_inno_languages/ChineseSimplified.isl
  assets/windows/unofficial_inno_languages/ChineseTraditional.isl
  assets/windows/unofficial_inno_languages/Croatian.isl
  assets/windows/unofficial_inno_languages/Galician.isl
  assets/windows/unofficial_inno_languages/Hungarian.isl
  assets/windows/unofficial_inno_languages/Indonesian.isl
  assets/windows/unofficial_inno_languages/Korean.isl
  assets/windows/unofficial_inno_languages/Latvian.isl
  assets/windows/unofficial_inno_languages/Swedish.isl
  gulpfile.js
  package.json
  yarn.lock
Labels: RN: Improvement

#1955 Rpm filters defaults
  locales/en/messages.json
  src/js/fc.js
  src/js/main.js
  src/js/tabs/configuration.js
  src/js/tabs/pid_tuning.js
  src/main.html
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1964 Initial FrSky ACCST V2.1.x support
  src/js/tabs/configuration.js
Labels: Needs coordination with betaflight, RN: Improvement

#2109 Gulp cordova generation and cleaning
  .gitignore
  README.md
  cordova/config_template.xml
  cordova/package_template.json
  gulpfile.js
Labels: RN: Improvement

#2108 Fixed message about non-supported firmware.
  locales/en/messages.json
Labels: RN: Bugfix

#2107 Updated version to 10.7.1 in maintenance branch.
  manifest.json
  package.json
Labels: Housekeeping

#2110 Move FC global vars inside FC object
  src/js/CliAutoComplete.js
  src/js/Features.js
  src/js/RateCurve.js
  src/js/TuningSliders.js
  src/js/backup_restore.js
  src/js/fc.js
  src/js/main.js
  src/js/model.js
  src/js/msp/MSPHelper.js
  src/js/peripherals.js
  src/js/protocols/stm32.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
Labels: RN: Refactoring

#2116 Cordova: use only version from package.json
  src/js/main.js
Labels: RN: Bugfix

#2114 Fix FC vars in Configuration tab
  src/js/tabs/configuration.js
Labels: RN: Bugfix

#2066 Auto adjust sensor texts size in header
  src/css/main.css
Labels: RN: Improvement

#2079 Update JQuery to 3.5.1 and other libraries to the last minor
  package.json
  yarn.lock
Labels: RN: Improvement

#2117 Cordova: add warning message when exiting the configurator
  locales/en/messages.json
  src/js/main.js
Labels: Android, RN: Improvement

#2115 Fix HSV tab in LED tab (Android App)
  src/js/tabs/led_strip.js
Labels: RN: Bugfix

#2122 Reverted THREE library to 0.97.0 to get CanvasRenderer back.
  package.json
  src/js/model.js
  src/main.html
  yarn.lock
Labels: RN: Bugfix

#2125 Adjust LQ OSD element preview according to selected serial RX provider
  src/js/tabs/osd.js
Labels: RN: Improvement

#2130 bump nwjs to latest version
  gulpfile.js
Labels: RN: Improvement

#2133 Fix css for large target names after Cordova changes
  src/css/main.css
Labels: RN: Improvement

#2134 Cordova/Android: improving logo and text position
  src/css/main.css
Labels: RN: Improvement

#2136 Fixed webview helper blocked on 'Checking webview applications' loader
  src/js/main_cordova.js
Labels: RN: Bugfix

#2138 Add Dutch translation
  assets/windows/installer.iss
  locales/en/messages.json
  locales/nl/messages.json
  src/js/localization.js
Labels: RN: New Language

#2139 Remove hard coded number
  src/js/fc.js
  src/js/tabs/configuration.js
  src/js/tabs/osd.js
Labels: RN: Improvement
