Repository betaflight/betaflight-configurator, pull requests merged in 2020-03, with the labels that each got.

#1902 Fix hiding accel features
  src/js/tabs/configuration.js
Labels: RN: Bugfix

#1901 Motor Output Limit and Profile Cell Count
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1904 Unified pid_titlebar_extended css style
  src/css/tabs/pid_tuning.css
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1903 Show warning on connect when ACC is not calibrated.
  locales/en/messages.json
  src/css/main.css
  src/js/fc.js
  src/js/serial_backend.js
  src/main.html
Labels: Needs coordination with betaflight, RN: Improvement

#1905 Dynamic Idle configurable
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1911 Updated documentation from template repository.
  .github/issue_template.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: documentation update

#1912 Removed the link to the legacy Chrome Web Store app.
  README.md
Labels: documentation update

#1909 Add rates type selection
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/images/rate_logos/actual.svg
  src/images/rate_logos/betaflight.svg
  src/images/rate_logos/kiss.svg
  src/images/rate_logos/quickrates.svg
  src/images/rate_logos/raceflight.svg
  src/js/RateCurve.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1914 Work around false error when claiming interface to fix firmware flashing on MacOS
  src/js/protocols/stm32usbdfu.js
Labels: RN: Bugfix

#1916 Log the reason for connection failures to analytics.
  src/js/serial_backend.js
Labels: RN: Improvement

#1913 Update KISS logo, rates type warning and deadband management
  locales/en/messages.json
  src/images/rate_logos/actual.svg
  src/images/rate_logos/kiss.svg
  src/js/RateCurve.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement

#1920 Fix OSD RSSI dBm element
  src/js/tabs/osd.js
Labels: RN: Bugfix

#1921 AG Gain default value to 3.5
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#1917 Fix weird behaviour on flashing tab.
  src/css/main.css
  src/main.html
Labels: RN: Bugfix

#1922 Add OSD_EFFICIENCY element
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement

#1923 Added warning when flashing unstable firmware.
  locales/en/messages.json
  src/css/main.css
  src/css/tabs/firmware_flasher.css
  src/js/tabs/firmware_flasher.js
  src/js/tabs/pid_tuning.js
  src/tabs/firmware_flasher.html
Labels: RN: Improvement

#1924 Added debug-release build for installers with debug console, changed Azure jobs to build them.
  assets/windows/installer.nsi
  azure-pipelines.yml
  gulpfile.js
Labels: build system improvement

#1928 Fixed azure build.
  azure-pipelines.yml
Labels: fixes broken build

#1926 Rename Efficiency to 'Battery efficiency'
  locales/en/messages.json
Labels: RN: Improvement

#1927 Improving osd chip detection warnings
  locales/en/messages.json
  src/css/main.css
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: Improvement

#1929 Update Azure Pipelines to allow release builds.
  azure-pipelines.yml
Labels: build system improvement

#1931 Fix rates type when switching BF version without rebooting the configurator
  src/js/tabs/pid_tuning.js
Labels: RN: Bugfix

#1930 Added the REDPINE SPI RX protocol. Also added SPI RX to analytics.
  src/js/tabs/configuration.js
Labels: RN: Improvement

#1934 Added none option to gps sbas
  locales/en/messages.json
  src/js/tabs/configuration.js
Labels: Needs coordination with betaflight, RN: Improvement

#1935 Disabled "Exit DFU Button" when no needed
  src/js/port_handler.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Improvement

#1938 Amended error highlighting in CLI.
  src/js/tabs/cli.js
Labels: RN: Improvement

#1941 Added VBat PID compensation to analytics.
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement

#1942 Added analytics for OSD elements.
  src/js/tabs/osd.js
Labels: RN: Improvement
