Repository betaflight/betaflight-configurator, pull requests merged in 2020-01, with the labels that each got.

#1848 Update Basque translation
  locales/eu/messages.json
Labels: RN: New Language

#1850 Sonar clean vtx.js
  src/js/tabs/vtx.js
Labels: Cleanup

#1849 Fix VTX when PowerLevel tag is empty
  src/js/tabs/vtx.js
Labels: RN: Bugfix

#1857 Changed installation procedure for Linux user
  README.md
Labels: documentation update

#1861 Workaround for H7 Rev.V weirdness on erase beyond 1MB
  src/js/protocols/stm32usbdfu.js
Labels: RN: Improvement

#1851 [MSP] Use MSP2_COMMON[_SET]_SERIAL_CONFIG for configuring ports
  src/js/injected_methods.js
  src/js/msp.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/ports.js
Labels: Needs coordination with betaflight, RN: Improvement

#1862 Update Catalan translation
  locales/ca/messages.json
Labels: Translation

#1863 Added button to exit DFU.
  locales/en/messages.json
  src/css/tabs/firmware_flasher.css
  src/js/port_handler.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/workers/hex_parser.js
  src/tabs/firmware_flasher.html
Labels: RN: Improvement

#1865 Fix problems introduced in #1851
  src/js/msp/MSPHelper.js
Labels: RN: Bugfix

#1867 Update MacOS instructions
  README.md
Labels: documentation update
