Repository betaflight/betaflight-configurator, pull requests merged in 2021-11, with the labels that each got.

#2634 Split header and fix i18n message
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/tabs/pid_tuning.html
Labels: Tested, RN: Bugfix, hacktoberfest-accepted

#2656 RFC feedforward max_rate_limit and jitter_factor
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Tested, RN: Improvement

#2638 rfc filter sliders
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Needs coordination with betaflight, Tested, RN: Improvement

#2489 Presets for Betaflight Configurator
  locales/en/messages.json
  package.json
  src/css/dark-theme.css
  src/css/main.css
  src/css/tabs/firmware_flasher.css
  src/css/tabs/options.css
  src/images/icons/cf_icon_check_orange.svg
  src/images/icons/cf_icon_search_orange.svg
  src/images/icons/cf_icon_welcome_orange.svg
  src/js/ConfigStorage.js
  src/js/data_storage.js
  src/js/gui.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/options.js
  src/main.html
  src/tabs/options.html
  src/tabs/presets/CliEngine.js
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.css
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.html
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
  src/tabs/presets/PickedPreset.js
  src/tabs/presets/PresetsRepoIndexed/PresetsGithubRepo.js
  src/tabs/presets/PresetsRepoIndexed/PresetsRepoIndexed.js
  src/tabs/presets/PresetsRepoIndexed/PresetsWebsiteRepo.js
  src/tabs/presets/SourcesDialog/PresetSource.js
  src/tabs/presets/SourcesDialog/SourcePanel.css
  src/tabs/presets/SourcesDialog/SourcePanel.html
  src/tabs/presets/SourcesDialog/SourcePanel.js
  src/tabs/presets/SourcesDialog/SourcesDialog.css
  src/tabs/presets/SourcesDialog/SourcesDialog.html
  src/tabs/presets/SourcesDialog/SourcesDialog.js
  src/tabs/presets/TitlePanel/PresetTitlePanel.css
  src/tabs/presets/TitlePanel/PresetTitlePanel.js
  src/tabs/presets/TitlePanel/PresetTitlePanelBody.html
  src/tabs/presets/presets.css
  src/tabs/presets/presets.html
  src/tabs/presets/presets.js
  yarn.lock
Labels: Ready to Merge, Tested, RN: Feature

#2660 Fix tab switching
  src/js/main.js
Labels: Ready to Merge, Tested, RN: Bugfix, Needs Approval

#2666 Fixed Android File System
  locales/en/messages.json
  src/js/cordova_chromeapi.js
Labels: Tested, RN: Bugfix, Android

#2655 RFC Dynamic Idle
  locales/en/messages.json
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
  src/tabs/motors.html
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Tested, RN: Improvement

#2650 Update azure windows image
  azure-pipelines.yml
Labels: Tested, RN: Improvement, build system improvement

#2673 Fix new feedforwardgroup options
  src/js/fc.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Tested, RN: Bugfix

#2670 Make timeout run conditional instead of allowing 0
  src/js/main.js
Labels: Tested, RN: Bugfix

#2668 Presets tab: minor fix border inside the detailed preset dialog
  src/tabs/presets/TitlePanel/PresetTitlePanel.js
Labels: Tested, RN: Bugfix
