Repository betaflight/betaflight-configurator, pull requests merged in 2021-12, with the labels that each got.

#2653 Remove Dynamic Notch from "Features"
  src/js/Features.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Needs coordination with betaflight, Tested, RN: Refactoring

#2671 Receiver tab update for 4.3
  locales/en/messages.json
  src/tabs/receiver.html
Labels: Tested, RN: Improvement

#2672 update pid_tuning page for 4.3
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Tested, RN: Improvement

#2676 [BUGFIX] Fix sliders disable input
  src/js/TuningSliders.js
Labels: Tested, RN: Bugfix

#2525 Verify addresses in hex files
  locales/en/messages.json
  src/js/protocols/stm32usbdfu.js
Labels: Tested, RN: Improvement

#2681 Indicate inactive dyn notch on looprates < 2kHz
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
Labels: Tested, RN: Bugfix

#2683 Bugfix: don't change filter type when moving filter slider
  src/js/TuningSliders.js
Labels: Ready to Merge, Tested, RN: Bugfix

#2678 Presets fix: remove cache for fetch
  src/tabs/presets/PresetsRepoIndexed/PresetsRepoIndexed.js
Labels: Tested, RN: Bugfix

#2665 Update github issues templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue_template.md
Labels: Tested, Housekeeping, RN: Refactoring

#2677 [BUG-FIX] Fix Port Detection using VID/PID
  locales/en/messages.json
  src/js/port_handler.js
  src/js/serial.js
  src/js/tabs/options.js
  src/tabs/options.html
Labels: Tested, RN: Bugfix

#2651 Fix integrated yaw usage
  src/js/TuningSliders.js
  src/js/tabs/pid_tuning.js
Labels: Tested, RN: Bugfix

#2687 Update debug field list names
  src/js/tabs/onboard_logging.js
Labels: Tested, RN: Bugfix

#2697 Dshot idle fix for versions < 4.3
  locales/en/messages.json
  src/js/tabs/motors.js
Labels: Tested, RN: Bugfix

#2367 chore: update to node 14
  .nvmrc
  .travis.yml
  README.md
  azure-pipelines.yml
  gulp-appdmg.js
  gulpfile.js
  package.json
  yarn.lock
Labels: Tested, RN: Improvement

#2698 Simplified Tuning update
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
Labels: Don't merge, Tested, RN: Bugfix

#2700 Presets FIX for loading broken BATCH configs - 'Save anyway' button did not work.
  src/tabs/presets/presets.js
Labels: Bugfix, Tested

#2603 Enhanced sat list for M8N/M9N
  locales/en/messages.json
  src/css/tabs/gps.css
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: Needs coordination with betaflight, RN: Improvement

#2695 Tidy up filter message text
  locales/en/messages.json
Labels: Tested, RN: Improvement

#2702 Fix duplicated i18n on filters tab
  locales/en/messages.json
  src/tabs/pid_tuning.html
Labels: Tested, RN: Bugfix

#2693 chore: add comman dangle rule for multiline
  .eslintrc.js
  gulpfile.js
  src/components/MotorOutputReordering/MotorOutputReorderingConfig.js
  src/js/Analytics.js
  src/js/Beepers.js
  src/js/CliAutoComplete.js
  src/js/Clipboard.js
  src/js/ConfigInserter.js
  src/js/ConfigStorage.js
  src/js/Features.js
  src/js/LogoManager.js
  src/js/backup_restore.js
  src/js/boards.js
  src/js/jenkins_loader.js
  src/js/main.js
  src/js/msp.js
  src/js/port_usage.js
  src/js/protocols/stm32.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/failsafe.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/gps.js
  src/js/tabs/landing.js
  src/js/tabs/led_strip.js
  src/js/tabs/map.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/receiver_msp.js
  src/js/tabs/sensors.js
  src/js/tabs/setup.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/js/utils/common.js
  src/js/utils/css.js
  src/js/utils/window_watchers.js
Labels: RN: Improvement

#2699 Fix DD and FF for legacy targets
  src/js/TuningSliders.js
Labels: For Discussion, Tested, RN: Bugfix

#2706 refactor: use js to generate table contents
  .sonarcloud.properties
  src/css/dark-theme.css
  src/css/main.css
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: Refactoring

#2679 Bump NW.js to 59.0
  gulpfile.js
Labels: RN: Improvement

#2708 Added EXPRESSLRS to the list of SPI protocols
  src/js/tabs/receiver.js
Labels: RN: New UI Element

#2630 Updated version to 10.7.2 in maintenance branch.
  manifest.json
  package.json
Labels: applied to branch, Tested, Housekeeping, hacktoberfest-accepted

#2657 10.7.1 bugfix: gyro slider
  src/js/TuningSliders.js
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Tested, RN: Bugfix

#2658 10.7.1 fix: long installation time
  assets/windows/UnInst.nsh
  assets/windows/bf_installer_small.bmp
  assets/windows/bf_uninstaller_icon.ico
  assets/windows/installer.iss
  assets/windows/installer.nsi
  assets/windows/unofficial_inno_languages/Basque.isl
  assets/windows/unofficial_inno_languages/ChineseSimplified.isl
  assets/windows/unofficial_inno_languages/ChineseTraditional.isl
  assets/windows/unofficial_inno_languages/Croatian.isl
  assets/windows/unofficial_inno_languages/Galician.isl
  assets/windows/unofficial_inno_languages/Hungarian.isl
  assets/windows/unofficial_inno_languages/Indonesian.isl
  assets/windows/unofficial_inno_languages/Korean.isl
  assets/windows/unofficial_inno_languages/Latvian.isl
  assets/windows/unofficial_inno_languages/Swedish.isl
  gulpfile.js
  package.json
  yarn.lock
Labels: Ready to Merge, RN: Bugfix

#2659 10.7.1 fix: Make tab_container scrollable when it is needed
  src/css/main.css
Labels: RN: Bugfix
