Repository betaflight/betaflight-configurator, pull requests merged in 2021-01, with the labels that each got.

#2355 Update board definitions
  src/js/boards.js
Labels: RN: Improvement

#2366 Fix auto AUX detection on Modes tab
  src/js/tabs/auxiliary.js
Labels: RN: Bugfix

#2320 Change lexical scope ports
  src/js/tabs/ports.js
Labels: RN: Improvement

#2296 Motor direction dialog for Dshot escs
  locales/en/messages.json
  src/components/EscDshotDirection/Body.html
  src/components/EscDshotDirection/EscDshotCommandQueue.js
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/components/EscDshotDirection/EscDshotDirectionMotorDriver.js
  src/components/EscDshotDirection/Styles.css
  src/components/MotorOutputReordering/MotorOutputReorderingComponent.js
  src/components/MotorOutputReordering/Styles.css
  src/css/dark-theme.css
  src/css/main.css
  src/css/tabs/motors.css
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/js/tabs/motors.js
  src/js/utils/CommonUtils.js
  src/js/utils/DshotCommand.js
  src/js/utils/EscProtocols.js
  src/main.html
  src/tabs/motors.html
Labels: RN: Feature

#2362 Fix led_strip overlay
  src/js/msp/MSPHelper.js
  src/js/tabs/led_strip.js
Labels: RN: Bugfix

#2347 Replace Stale bot by action
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: Has Milestone, Housekeeping

#2376 Fix esc direction dialog on Android
  src/css/main.css
  src/css/tabs/motors.css
Labels: RN: Bugfix

#2378 Fix hover/drag-after-push bug for buttons for Motor Direction dialog on Android
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/components/EscDshotDirection/Styles.css
Labels: RN: Bugfix

#2374 Add missing filters
  src/js/fc.js
Labels: RN: Improvement

#2380 Failed to close serial port (virtual mode)
  src/js/serial.js
Labels: RN: Bugfix

#2349 Display SmartAudio version on VTX tab (Configurator part)
  locales/en/messages.json
  src/js/fc.js
  src/js/gui.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/vtx.js
  src/js/utils/VtxDeviceStatus/Rtc6705DeviceStatus.js
  src/js/utils/VtxDeviceStatus/SmartAudioDeviceStatus.js
  src/js/utils/VtxDeviceStatus/TrampDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatusFactory.js
  src/main.html
Labels: RN: Improvement

#2383 Fix VirtualFC TypeError
  src/js/VirtualFC.js
Labels: RN: Bugfix

#2302 Allows the user to always open the last tab that was used *before* the CLI tab.
  src/js/gui.js
  src/js/main.js
Labels: Inactive, RN: Improvement

#1821 Add support for firmware side sliders
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Has Milestone, RN: Improvement
