Repository betaflight/betaflight-configurator, pull requests merged in 2021-06, with the labels that each got.

#2483 Fix typing behaviour on PID inputs
  src/js/TuningSliders.js
Labels: RN: Bugfix

#2465 Mcu ID for lua vtx table
  locales/en/messages.json
  src/js/tabs/vtx.js
Labels: RN: Improvement

#2495 Put keyboard focus on the 'Close' button of the problems dialog.
  src/js/serial_backend.js
Labels: RN: Improvement

#2505 Update Azure Linux build version to latest
  azure-pipelines.yml
Labels: Ready to Merge, Tested, build system improvement

#2502 Updated Actual default values
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement, Tested

#2497 Prevent drag/dop and text selection on most elements.
  src/css/main.css
  src/css/tabs/cli.css
Labels: RN: Bugfix, Tested

#2460 Filter MSP Output while opening CLI
  src/js/tabs/cli.js
Labels: RN: Improvement, Ready to Merge, Tested

#2503 Added PT2 and PT3 filter types
  src/js/tabs/pid_tuning.js
Labels: RN: Improvement, Tested

#2471 Fix OSD speed unit preview
  src/js/tabs/osd.js
Labels: RN: Bugfix, Ready to Merge, Tested

#2427 OSD Tx Uplink Power support
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: Improvement, Ready to Merge, Tested

#2468 Add support for OSD elements variants
  locales/en/messages.json
  src/css/tabs/osd.css
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: Improvement, Tested

#2501 feat: move firmware to modules
  src/js/main.js
  src/js/tabs/firmware_flasher.js
  src/main.html
Labels: RN: Improvement, Tested

#2441 cordova_serial.requestPermission() driver fix
  cordova/usb_device_filter.xml
  src/js/cordova_chromeapi.js
Labels: Android, RN: Improvement, Tested

#2514 Refactor preview of osd battery usage
  src/js/tabs/osd.js
Labels: RN: Refactoring, Tested

#2513 Rebase of firmware_flasher.js
  src/js/tabs/firmware_flasher.js
Labels: RN: Refactoring, Tested

#2507 Updated NW.js to 0.54.0.
  gulpfile.js
Labels: RN: Improvement, Tested

#2504 Update Dshot Bidir autodefaults and dynamic notch options
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, RN: Improvement, Tested

#2516 Fix css height after update NWjs to 0.54
  src/css/main.css
Labels: RN: Bugfix, Tested

#2485 Verify board from firmware before flashing
  locales/en/messages.json
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/serial.js
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: Feature, Tested

#2475 Make connection timeout user-configurable
  locales/en/messages.json
  src/css/tabs/options.css
  src/js/port_handler.js
  src/js/serial_backend.js
  src/js/tabs/options.js
  src/tabs/options.html
Labels: RN: Feature, Tested

#2436 Validate motor outputs and reset mixer if not enough resources available
  locales/en/messages.json
  src/css/tabs/motors.css
  src/js/tabs/motors.js
  src/tabs/motors.html
Labels: RN: Improvement, Tested

#2511 Update Feedforward to new names and values
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Improvement, Tested
