Repository betaflight/betaflight-configurator, pull requests merged in 2021-08, with the labels that each got.

#2543 Adjust Modes Name CSS min-width
  src/css/tabs/auxiliary.css
  src/js/port_handler.js
  src/js/tabs/auxiliary.js
  src/js/utils/common.js
Labels: RN: Bugfix, Tested

#2531 Disable feedforward switch action for old versions
  src/css/switchery_custom.css
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: Bugfix, Tested

#2524 Detect board in firmware_flasher patch
  locales/en/messages.json
  src/css/tabs/firmware_flasher.css
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/serial.js
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: Bugfix, Tested

#2522 Added latest Rc Smoothing changes
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: Improvement, Tested

#2558 Removed unneeded BOXNAME polling.
  src/js/serial_backend.js
Labels: Tested, RN: Improvement

#2556 Added Analytics Tracking for Each 'Save' Button Click that Tracks Changes.
  src/js/Analytics.js
  src/js/tabs/configuration.js
  src/js/tabs/motors.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/vtx.js
Labels: Tested, RN: Improvement

#2553 Fix Expert Mode Switch
  src/js/main.js
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: Bugfix

#2568 Add cordova-chrome-sockets-tcp
  cordova/package_template.json
  cordova/yarn.lock
Labels: Tested, RN: Improvement, Android

#2573 Keep in sync azure used Ubuntu Version
  azure-pipelines.yml
Labels: Tested, RN: Improvement, build system improvement

#2548 Bump NWjs to 0.54.1
  gulpfile.js
Labels: Tested, RN: Bugfix
