Repository betaflight/betaflight-configurator, pull requests merged in 2021-09, with the labels that each got.

#2563 Change mixer
  locales/en/messages.json
  src/js/tabs/motors.js
  src/js/utils/common.js
Labels: Tested, RN: Bugfix

#2574 Standardised configurator version naming.
  cordova/config_template.xml
  gulpfile.js
  locales/en/messages.json
  package.json
  src/components/status-bar/StatusBar.vue
  src/components/status-bar/StatusBarVersion.vue
  src/js/Analytics.js
  src/js/data_storage.js
  src/js/main.js
  src/js/serial_backend.js
  src/main.html
  yarn.lock
Labels: Tested, RN: Improvement

#2577 Added build for Android Play store bundle.
  .gitignore
  azure-pipelines.yml
  cordova/build.json
  cordova/build_template.json
  cordova/config_template.xml
  cordova/debug.keystore
  cordova/release.keystore
  gulpfile.js
  package.json
  src/js/main.js
  yarn.lock
Labels: Tested, RN: Improvement, build system improvement

#2582 Fix webview problem in the Android version.
  cordova/package_template.json
  cordova/yarn.lock
Labels: Tested, RN: Bugfix

#2607 Added yarn gulp debug-no-start command
  gulpfile.js
Labels: Tested, RN: Improvement, build system improvement

#2561 Fix reconnection issue in cli
  src/js/main.js
  src/js/msp.js
  src/js/serial.js
  src/js/serial_backend.js
Labels: Tested, RN: Bugfix

#2570 Rebase stm32.js
  src/js/protocols/stm32.js
  src/js/release_checker.js
Labels: Tested, RN: Refactoring

#2554 Remove scrolling conditional and allow auto-detect board when no board selected
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: Feature

#2572 New PID sliders and changed defaults
  locales/en/messages.json
  src/css/tabs/pid_tuning.css
  src/js/TuningSliders.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
  src/js/utils/common.js
  src/tabs/pid_tuning.html
Labels: Needs coordination with betaflight, Tested, RN: Improvement
