Repository betaflight/betaflight-configurator, pull requests merged in 2022-08, with the labels that each got.

#2953 Remove antiGravityMode and change iTermAcceleratorGain to antiGravityGain
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3002 Add `no-extra-semi` to match what's in sonarcloud
  .eslintrc.js
Labels: build system improvement

#3000 Tidy up `init.js` build order
  gulpfile.js
  src/js/main.js
  src/main.html
Labels: RN: REFACTOR

#2999 Remove css utils from global scope
  src/js/tabs/pid_tuning.js
  src/js/utils/css.js
  src/main.html
Labels: RN: REFACTOR

#2930 Update NWjs to 0.67.1 and Node to 16.17.0 LTS
  .nvmrc
  gulpfile.js
  src/js/gui.js
Labels: RN: BUILD SYSTEM

#3006 Fix semicolon
  src/js/utils/css.js
Labels: RN: BUGFIX
