Repository betaflight/betaflight-configurator, pull requests merged in 2022-02, with the labels that each got.

#2791 Update translations
  locales/ca/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/hu/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: RN: Translations update

#2792 Hide second iterm relax tooltip
  src/css/tabs/pid_tuning.css
  src/tabs/pid_tuning.html
Labels: RN: Bugfix

#2790 Presets: hack-fix for multiple select dropdowns with 199+ elements
  src/tabs/presets/presets.js
Labels: RN: Bugfix

#2783 ci: Remove publish unit tests
  .github/workflows/ci.yml
Labels: RN: Build System Improvement

#2785 Make CI a reusable workflow
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/pr.yml
Labels: RN: Build System Improvement

#2795 Upgrade stale bot action to version 4
  .github/workflows/stale.yaml
Labels: RN: Improvement

#2800 Update translations
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/ja/messages.json
Labels: RN: Translations update

#2811 Remove CI name to be equal than tag
  .github/workflows/nightly.yml
Labels: Tested, RN: Build System Improvement

#2813 Artifact links comment github workflow
  .github/workflows/artifact-links.yml
  .github/workflows/ci.yml
Labels: Tested, RN: Build System Improvement

#2817 Fix dshot bidir switch
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
Labels: Tested, RN: Bugfix

#2820 Update translations
  locales/gl/messages.json
  locales/ko/messages.json
Labels: RN: Translations update

#2818 Hide old artifact links
  .github/workflows/pr.yml
Labels: RN: Build System Improvement

#2828 Firmware flasher fix for the release notes show
  src/js/tabs/firmware_flasher.js
Labels: RN: Bugfix

#2758 Fix reboot
  src/js/backup_restore.js
  src/js/msp.js
  src/js/protocols/stm32.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/ports.js
  src/js/tabs/receiver.js
  src/js/tabs/transponder.js
Labels: Tested, RN: Bugfix

#2814 Replace travis/azure badge by action one
  README.md
Labels: Tested, RN: Build System Improvement

#2830 Create new workflow to hide artifact links
  .github/workflows/hide-artifact-links.yml
  .github/workflows/pr.yml
Labels: RN: Build System Improvement

#2829 Fix RX model preview for different rates system
  src/js/fc.js
  src/js/tabs/receiver.js
Labels: RN: Bugfix

#2831 Update translations
  locales/ko/messages.json
Labels: RN: Translations update

#2836 check every 100ms for DFU mode
  src/js/protocols/stm32.js
Labels: Tested, RN: Improvement
