Repository betaflight/betaflight-configurator, pull requests merged in 2022-12, with the labels that each got.

#3099 Update translations
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: RN: TRANSLATION

#3102 Fix local flashing messaging
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3096 Update MSP2TEXT command
  src/js/backup_restore.js
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/configuration.js
  src/js/tabs/onboard_logging.js
Labels: Cleanup, Ready to Merge

#3095 Fix elrs connection
  cordova/config_template.xml
  src/js/mdns_discovery.js
  src/js/port_handler.js
  src/js/serial_backend.js
  src/main.html
Labels: Testing Required, RN: BUGFIX

#3111 Fix 2 typos
  locales/en/messages.json
Labels: Ready to Merge, RN: BUGFIX

#3106 Fix HD selection in UI
  src/js/msp/MSPHelper.js
  src/js/tabs/osd.js
Labels: Ready to Merge, RN: BUGFIX

#3097 Add support for ELRS UID
  .eslintrc.js
  gulpfile.js
  locales/en/messages.json
  package.json
  src/css/tabs/receiver.less
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
  yarn.lock
Labels: Ready to Merge, RN: FEATURE

#3101 Fix OSD preview
  src/css/tabs/osd.less
Labels: Ready to Merge, RN: BUGFIX

#3116 Upgrade action-gh-release to latest version
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: Housekeeping

#3115 Move babel module to devDependency
  package.json
Labels: dependencies

#3113 Action to create a PR with translations
  .github/workflows/translations-pr.yml
  crowdin.yml
Labels: Translation, Housekeeping

#3118 Fix virtual OSD elements and OSD backwards compability bug
  src/js/VirtualFC.js
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3124 Constrain rates minimum setting
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#3121 Add action to upload messages file to Crowdin
  .github/workflows/nightly.yml
  .github/workflows/translations-pr.yml
  .github/workflows/translations-upload.yml
  crowdin.yml
Labels: Translation, Housekeeping

#3129 Fix secrets in Crowdin actions
  .github/workflows/nightly.yml
  .github/workflows/translations-upload.yml
Labels: Housekeeping

#3128 Remove setup-node cache
  .github/workflows/ci.yml
Labels: Housekeeping

#3104 Bump API_VERSION_ACCEPTED and semver cleanup
  locales/en/messages.json
  src/css/tabs/setup.less
  src/js/Beepers.js
  src/js/CliAutoComplete.js
  src/js/Features.js
  src/js/RateCurve.js
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/transponder.js
  src/main.html
  src/tabs/sensors.html
  src/tabs/setup.html
Labels: Cleanup, Ready to Merge

#3134 Restore experimental backup and restore only for virtual and fw below 4.3
  locales/en/messages.json
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
  src/js/tabs/osd.js
  src/js/tabs/setup.js
  src/js/utils/EscProtocols.js
  src/js/utils/common.js
  src/main.html
  src/tabs/setup.html
Labels: Cleanup

#3139 Housekeeping: Updating some messaging labels.
  locales/en/messages.json
Labels: Cleanup, RN: IMPROVEMENT, Housekeeping

#3140 Fix receiver provider order
  src/js/fc.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/setup.js
Labels: Cleanup

#3142 FIX: Load firmware online button not enabled if not in expert mode
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3144 FIX: Commit selection should not be available unless prerelease
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: BUGFIX

#3133 Add DEBUG_ANGLEMODE
  src/js/tabs/onboard_logging.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3146 Update MCU types
  src/js/fc.js
Labels: Housekeeping

#3147 More descriptive Reset Settings warning
  locales/en/messages.json
  src/css/main.less
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#3148 Remove Google Analytics
  libraries/analytics.js
  src/js/Analytics.js
  src/js/CliAutoComplete.js
  src/js/Features.js
  src/js/backup_restore.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/options.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/setup.js
  src/js/tabs/setup_osd.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/main.html
  src/tabs/options.html
Labels: Cleanup

#3149 Always request hex via the post to API mechanism
  src/js/release_loader.js
  src/js/tabs/firmware_flasher.js
Labels: RN: REFACTOR

#3150 Fields for PID and rate profile names.
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Tested, RN: BUGFIX, RN: IMPROVEMENT

#3153 Fix dynamic filter
  src/js/tabs/motors.js
Labels: Cleanup, Hotfix

#3158 Fixes nightly build badge
  README.md
Labels: Hotfix, Housekeeping

#3157 repackage .deb with xz compression
  .github/workflows/ci.yml
Labels: RN: BUGFIX

#3159 BUILD: Automatically add the tag for the version (if not a debug build).
  .github/workflows/ci.yml
Labels: build system improvement, Housekeeping

#3155 Bump gulp-debian library
  .github/workflows/ci.yml
  gulpfile.js
  package.json
  test/configs/opt/etc/dummy.cfg
  yarn.lock
Labels: build system improvement, dependencies

#3161 IMPROVEMENT: As per suggestion, one RX protocol, and one Telem protocol
  locales/en/messages.json
  src/css/tabs/firmware_flasher.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: UI, RN: IMPROVEMENT

#3165 UI: Move motor protocol to single option
  locales/en/messages.json
  src/css/tabs/firmware_flasher.less
  src/tabs/firmware_flasher.html
Labels: RN: UI

#3174 Fix warnings display
  src/tabs/pid_tuning.html
Labels: RN: UI

#3167 Update sort function
  src/js/tabs/motors.js
  src/js/tabs/receiver.js
  src/js/utils/common.js
Labels: RN: REFACTOR

#3001 Chore/move gui to modules
  .gitignore
  src/js/Clipboard.js
  src/js/gui.js
  src/js/localization.js
  src/js/main.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/gps.js
  src/js/tabs/help.js
  src/js/tabs/landing.js
  src/js/tabs/led_strip.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/options.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/setup_osd.js
  src/js/tabs/static_tab.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/main.html
  src/tabs/presets/presets.js
  test/karma.conf.js
Labels: Tested, RN: REFACTOR

#3177 Language sort optionslist at power tab
  src/js/tabs/power.js
  src/tabs/power.html
Labels: RN: UI

#3179 Rollup improvements
  gulpfile.js
  package.json
  yarn.lock
Labels: build system improvement, RN: BUILD SYSTEM

#3180 fix: cordova browserify/rollup conflict
  gulpfile.js
  package.json
  yarn.lock
Labels: RN: BUGFIX

#3182 Fix local download of hex file
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3183 Presets fix: removed old event listener that caused console errors
  src/tabs/presets/presets.js
Labels: RN: BUGFIX

#3178 Language sort optionlist at LED tab
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: RN: UI

#3184 Fix Android receiver tab (replace MD5 library)
  .eslintrc.js
  package.json
  src/js/tabs/receiver.js
  yarn.lock
Labels: RN: BUGFIX

#3175 Fix tooltip
  locales/en/messages.json
  src/js/utils/common.js
  src/tabs/firmware_flasher.html
Labels: RN: UI
