Repository betaflight/betaflight-configurator, pull requests merged in 2022-06, with the labels that each got.

#2944 Fix display of OSD tab save/font buttons on Android.
  src/tabs/osd.html
Labels: RN: BUGFIX

#2945 Update translations
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: RN: TRANSLATION

#2941 Remove sensitivity
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#2835 Update API to 1.45
  src/js/data_storage.js
Labels: Housekeeping

#2927 Upgrade NwBuilder to version 3.7.4
  package.json
  yarn.lock
Labels: RN: BUILD SYSTEM

#2926 Update all workflows to use ubuntu-22.04
  .github/workflows/ci.yml
  .github/workflows/stale.yaml
Labels: RN: BUILD SYSTEM

#2943 Minor changes to logging tab. More information and one correction
  src/tabs/logging.html
Labels: RN: IMPROVEMENT

#2846 Fix MSP flow, make MSP timeout dynamic
  src/js/msp.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX, RN: IMPROVEMENT

#2960 Update dependencies
  package.json
  yarn.lock
Labels: dependencies

#2956 Update appdmg to version 0.6.4
  package.json
  yarn.lock
Labels: dependencies
