Repository betaflight/betaflight-configurator, pull requests merged in 2022-09, with the labels that each got.

#2965 VTX Device over MSP
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/ports.js
  src/js/tabs/vtx.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxMspDeviceStatus.js
Labels: Needs coordination with betaflight, RN: FEATURE

#2969 Remove STM32 driver link
  locales/en/messages.json
Labels: Housekeeping

#2922 scanning for elrs network devices with crsf msp frame capability
  cordova/config_template.xml
  cordova/package_template.json
  package.json
  src/js/port_handler.js
  src/main.html
  yarn.lock
Labels: Tested, RN: IMPROVEMENT

#2952 hide accel related items when accel disabled
  src/js/tabs/pid_tuning.js
  src/tabs/configuration.html
Labels: RN: BUGFIX

#2980 Extended Bidir Dshot
  src/js/tabs/motors.js
Labels: RN: IMPROVEMENT

#2998 Fix profile switching
  src/js/tabs/pid_tuning.js
Labels: Tested, RN: BUGFIX

#3011 Add missing debug modes
  src/js/tabs/onboard_logging.js
Labels: RN: FEATURE

#3018 Fix OSD checkbox
  src/css/dark-theme.less
Labels: RN: BUGFIX

#3020 Change dynamic Notch MinHz Default
  src/js/fc.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#2993 Fix auto_profile_cell_count range
  locales/en/messages.json
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Tested, RN: BUGFIX

#2964 vtx_osd_variant_fix
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#2987 Raise PID profile count
  src/js/tabs/pid_tuning.js
Labels: RN: FEATURE

#2985 Raise upper limit of dyn_idle_min_rpm
  src/js/tabs/pid_tuning.js
Labels: RN: IMPROVEMENT

#3025 fix: expose OSD for virtual FC to pick up
  src/js/tabs/osd.js
Labels: RN: BUGFIX
