Repository betaflight/betaflight-configurator, pull requests merged in 2022-11, with the labels that each got.

#3065 Change 'VTX (MSP)' to 'VTX (MSP + Displayport)' and lose 'OSD (MSP Displayport)' option
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/ports.js
Labels: RN: BUGFIX

#3066 Restoring ability to load local configuration for a target
  locales/en/messages.json
  src/js/ConfigInserter.js
  src/js/tabs/firmware_flasher.js
  src/main.html
  src/tabs/firmware_flasher.html
Labels: Ready to Merge, Tested

#3067 release_notes - correctly state that nightly is a debug release
  .github/workflows/nightly.yml
Labels: Ready to Merge, Housekeeping

#3060 Add GPS DOP debug
  src/js/tabs/onboard_logging.js
Labels: Ready to Merge, RN: IMPROVEMENT

#3068 Fixed board selection not sticking
  src/js/tabs/firmware_flasher.js
Labels: BUG, Cleanup, Tested

#3070 Adding help icons and improving darkmode css.
  locales/en/messages.json
  src/css/dark-theme.less
  src/tabs/firmware_flasher.html
Labels: Housekeeping

#3074 Adding custom define input box
  locales/en/messages.json
  src/css/dark-theme.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: Feature Request, Ready to Merge, Tested, build system improvement

#3069 Allow user to specify a sha / pull request
  src/js/tabs/firmware_flasher.js
Labels: Housekeeping

#3073 Fix scale for gyro readings
  src/js/tabs/motors.js
  src/tabs/sensors.html
Labels: Ready to Merge, RN: BUGFIX

#3076 Fix gps_rescue_min_start_dist
  src/js/tabs/failsafe.js
Labels: Ready to Merge, RN: BUGFIX

#3080 Update translations
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/hr/messages.json
  locales/id/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/lv/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/sv/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: RN: TRANSLATION

#3079 10.8 Presets bugfix: automatically preselect current FC firmware version
  src/tabs/presets/presets.js
Labels: RN: BUGFIX

#3078 Fix TPA
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: Ready to Merge, Tested, RN: BUGFIX

#3081 Adding a progress bar for CLOUD BUILD progress
  locales/en/messages.json
  src/css/dark-theme.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: Tested, RN: IMPROVEMENT, RN: BUILD SYSTEM

#2840 Enable or disable features according to port configuration
  src/js/Features.js
  src/js/tabs/ports.js
Labels: RN: FEATURE

#3084 Fix serialportconfig
  src/js/serial_backend.js
  src/js/tabs/ports.js
Labels: RN: BUGFIX

#3087 Adding ability to specify a classic build
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: build system improvement

#3089 Few CSS fixes for firmware flasher -> build configuration
  src/css/dark-theme.less
  src/css/tabs/firmware_flasher.less
  src/tabs/firmware_flasher.html
Labels: enhancement

#3071 Add HD OSD support
  locales/en/messages.json
  src/css/dark-theme.less
  src/css/tabs/osd.less
  src/images/osd-bg-1-grid-ntsc.png
  src/images/osd-bg-1-grid-pal.png
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: FEATURE

#3088 Fix RSNR
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Tested, RN: BUGFIX

#3091 Firmware flasher: classic build toggle - moved to build configuration header
  src/css/main.less
  src/css/tabs/firmware_flasher.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: enhancement
