Repository betaflight/betaflight-configurator, pull requests merged in 2022-07, with the labels that each got.

#2962 Use Fedora/RHEL names for RPM deps
  gulpfile.js
Labels: build system improvement

#2940 Bump Arm build to ARMv8
  README.md
  gulpfile.js
Labels: RN: BUILD SYSTEM

#2967 Fix cpuload
  src/js/serial_backend.js
Labels: RN: BUGFIX

#2961 Remove disable minimize workaround on MacOS
  src/js/main.js
Labels: RN: BUGFIX

#2464 Move every tab to modules
  src/js/main.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/setup_osd.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/main.html
  src/tabs/presets/presets.js
  test/karma.conf.js
Labels: RN: IMPROVEMENT

#2970 Fix motor stop
  src/js/msp/MSPHelper.js
  src/js/tabs/motors.js
Labels: RN: BUGFIX

#2983 Fix cli output, reboot and timeout
  src/js/backup_restore.js
  src/js/gui.js
  src/js/main.js
  src/js/msp.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/ports.js
  src/js/tabs/receiver.js
  src/js/tabs/transponder.js
Labels: Tested, RN: BUGFIX
