Repository betaflight/betaflight-configurator, pull requests merged in 2023-06, with the labels that each got.

#3467 Removing unused git_info section
  src/css/tabs/firmware_flasher.less
  src/css/tabs/osd.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: UI, Housekeeping

#3468 Add sponsor tile to firmware flashing tab
  src/css/main.less
  src/images/sponsors/dogcom.svg
  src/images/sponsors/hqprop.svg
  src/images/sponsors/radiomaster.svg
  src/js/BuildApi.js
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: UI

#3470 use-select2
  src/css/tabs/onboard_logging.less
  src/js/tabs/onboard_logging.js
Labels: RN: UI

#3481 fix language variable name firmwareFlasherBoardVerificationFail
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3473 Tabs to spaces in less files, and renaming logo files (cf to bf).
  src/css/dark-theme.less
  src/css/main.less
  src/css/main_cordova.less
  src/css/select2_custom.less
  src/css/switchery_custom.less
  src/images/bf_logo_black.svg
  src/images/bf_logo_white.svg
  src/images/bf_settings_black.svg
  src/images/bf_settings_white.svg
  src/tabs/landing.html
Labels: Housekeeping

#3477 Adding sponsor program images (for future use).
  src/images/sponsors/bf_hardware_seal_dark.svg
  src/images/sponsors/bf_hardware_seal_light.svg
  src/images/sponsors/bf_partner_dark.svg
  src/images/sponsors/bf_partner_light.svg
Labels: RN: UI

#3480 Fix offline behavior
  locales/en/messages.json
  src/js/Features.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/setup.js
  src/js/utils/updateTabList.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3459 Backup config on flash
  locales/en/messages.json
  src/js/port_handler.js
  src/js/tabs/firmware_flasher.js
  src/js/utils/generate_filename.js
Labels: Tested, RN: IMPROVEMENT

#3475 Flasher tab: remember last user selected radio protocol
  src/js/tabs/firmware_flasher.js
Labels: Rebase Required

#3482 Fix MSP rx sticks window
  gulpfile.js
  locales/en/messages.json
  src/css/tabs/receiver_msp.less
  src/js/tabs/receiver_msp.js
  src/tabs/receiver_msp.html
Labels: RN: BUGFIX

#3489 Add RPM debugField
  src/js/tabs/onboard_logging.js
Labels: RN: IMPROVEMENT

#3474 Upgrade stale action to v8
  .github/workflows/stale.yaml
Labels: Housekeeping

#3483 Cancel previous execution of PR github action
  .github/workflows/pr.yml
Labels: Housekeeping

#3476 Add support for multiple presets repositories to be active at once
  locales/en/messages.json
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
  src/tabs/presets/FavoritePresets.js
  src/tabs/presets/PickedPreset.js
  src/tabs/presets/PresetsRepoIndexed/PresetsGithubRepo.js
  src/tabs/presets/PresetsRepoIndexed/PresetsRepoIndexed.js
  src/tabs/presets/PresetsRepoIndexed/PresetsWebsiteRepo.js
  src/tabs/presets/SourcesDialog/SourcePanel.html
  src/tabs/presets/SourcesDialog/SourcePanel.js
  src/tabs/presets/SourcesDialog/SourcesDialog.js
  src/tabs/presets/TitlePanel/PresetTitlePanel.css
  src/tabs/presets/TitlePanel/PresetTitlePanel.js
  src/tabs/presets/TitlePanel/PresetTitlePanelBody.html
  src/tabs/presets/presets.html
  src/tabs/presets/presets.js
Labels: Ready to Merge, RN: IMPROVEMENT

#3485 Add help text to sections on GPS tab
  locales/en/messages.json
  src/tabs/gps.html
Labels: RN: UI

#3495 Fix API version
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: BUGFIX

#3498 Fix OSD stat elements
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3496 Fix loading of preset title panel callback
  src/tabs/presets/TitlePanel/PresetTitlePanel.js
Labels: RN: BUGFIX

#3497 Fix pit mode frequency
  src/js/tabs/vtx.js
Labels: Tested, RN: BUGFIX
