Repository betaflight/betaflight-configurator, pull requests merged in 2023-01, with the labels that each got.

#3195 UI: HTML cleanup based on prettier output
  src/tabs/configuration.html
  src/tabs/firmware_flasher.html
  src/tabs/gps.html
  src/tabs/landing.html
  src/tabs/pid_tuning.html
Labels: RN: UI

#3201 FIX: Update spelling error in code
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/en/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
  src/css/tabs/firmware_flasher.less
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: Cleanup, RN: REFACTOR

#3189 Refactor config storage to use modules
  src/js/ConfigStorage.js
  src/js/gui.js
  src/js/localization.js
  src/js/main.js
  src/js/tabs/auxiliary.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/help.js
  src/js/tabs/landing.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/options.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/main.html
  src/tabs/presets/presets.js
Labels: RN: REFACTOR

#3203 Fix for OSD grid overflowing the preview area as per #3202
  src/css/tabs/osd.less
Labels: RN: UI

#3191 Use esm modules for session storage
  src/js/SessionStorage.js
  src/js/main.js
  src/js/release_checker.js
  src/js/release_loader.js
  src/js/tabs/firmware_flasher.js
  src/main.html
Labels: Rebase Required, RN: REFACTOR

#3206 Adding a support submission button on CLI to assist in support
  locales/en/messages.json
  src/js/BuildApi.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/tabs/cli.html
Labels: enhancement, Tested, RN: UI, RN: IMPROVEMENT

#3205 FIX: Android APK missing from RC3
  .github/workflows/ci.yml
Labels: RN: BUGFIX, fixes broken build, Android

#3198 Flasher tab: fix wiki button
  src/js/gui.js
Labels: RN: UI

#3212 FIX: Incorrect naming
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3211 Sort of 3 optionlist at failsafe tab
  src/js/tabs/failsafe.js
  src/tabs/failsafe.html
Labels: RN: IMPROVEMENT

#3215 UI: Apply custom config defaults based on build options
  .gitignore
  src/js/BuildApi.js
  src/js/tabs/firmware_flasher.js
Labels: RN: UI, RN: IMPROVEMENT

#3187 Show wiki to target, ie. Board---FRSKYF4
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: UI

#2726 Convert battery icon to vue component
  .storybook/preview.js
  src/components/init.js
  src/components/quad-status/BatteryIcon.stories.js
  src/components/quad-status/BatteryIcon.vue
  src/components/quad-status/BatteryLegend.stories.js
  src/css/main.less
  src/css/theme.css
  src/js/serial_backend.js
  src/main.html
Labels: Tested, RN: UI

#3216 Translation key fixes
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/ru/messages.json
  locales/zh_CN/messages.json
  locales/zh_TW/messages.json
Labels: Translation, RN: TRANSLATION

#3220 FIX: removing duplicate language key
  locales/en/messages.json
Labels: Cleanup, RN: TRANSLATION

#3219 portsTab: sort telemetry, sensors, peripherals select lists
  src/js/tabs/ports.js
Labels: RN: UI

#3222 RF: Moved Analytics to class
  src/js/Analytics.js
  src/js/CliAutoComplete.js
  src/js/Features.js
  src/js/backup_restore.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/setup_osd.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/main.html
  test/tabs/cli.js
Labels: Cleanup, Work in Progress, RN: REFACTOR

#3224 fix TPA-Mode display
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#3192 Serial backend modules
  src/components/MotorOutputReordering/MotorOutputReorderingComponent.js
  src/components/init.js
  src/js/Beepers.js
  src/js/Features.js
  src/js/VirtualFC.js
  src/js/backup_restore.js
  src/js/fc.js
  src/js/main.js
  src/js/msp/MSPConnector.js
  src/js/msp/MSPHelper.js
  src/js/protocols/stm32.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/main.html
  test/karma.conf.js
Labels: Tested, RN: REFACTOR

#3208 Refactor vtx device status
  src/js/msp/MSPHelper.js
  src/js/tabs/vtx.js
  src/js/utils/VtxDeviceStatus/Rtc6705DeviceStatus.js
  src/js/utils/VtxDeviceStatus/SmartAudioDeviceStatus.js
  src/js/utils/VtxDeviceStatus/TrampDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatusFactory.js
  src/js/utils/VtxDeviceStatus/VtxMspDeviceStatus.js
  src/main.html
Labels: Tested, RN: REFACTOR

#3221 Fix OSD preview for Android
  src/css/tabs/osd.less
Labels: RN: UI

#3228 Fix motor testing
  src/js/tabs/motors.js
Labels: RN: BUGFIX

#3235 Motor reorder dialog fix: importing serial backend
  src/components/MotorOutputReordering/MotorOutputReorderingComponent.js
Labels: Cleanup

#3236 Refactor. Core build mode.
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/en/messages.json
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/pt/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: Cleanup, RN: REFACTOR

#3237 Add new wiki to configurator tabs
  src/js/gui.js
  src/js/tabs/firmware_flasher.js
Labels: RN: UI, Housekeeping

#3239 Add center crosshair to the OSD helper lines
  src/css/tabs/osd.less
Labels: RN: UI

#3245 feat: use modules instead of global bindings
  .eslintrc.js
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/components/MotorOutputReordering/MotorOutputReorderingComponent.js
  src/js/Analytics.js
  src/js/CliAutoComplete.js
  src/js/DarkTheme.js
  src/js/Features.js
  src/js/LogoManager.js
  src/js/RateCurve.js
  src/js/TuningSliders.js
  src/js/VirtualFC.js
  src/js/backup_restore.js
  src/js/fc.js
  src/js/gui.js
  src/js/main.js
  src/js/msp/MSPHelper.js
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/auxiliary.js
  src/js/tabs/cli.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/gps.js
  src/js/tabs/help.js
  src/js/tabs/landing.js
  src/js/tabs/led_strip.js
  src/js/tabs/logging.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/options.js
  src/js/tabs/osd.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/js/tabs/servos.js
  src/js/tabs/setup.js
  src/js/tabs/setup_osd.js
  src/js/tabs/static_tab.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
  src/js/utils/EscProtocols.js
  src/js/utils/VtxDeviceStatus/VtxMspDeviceStatus.js
  src/js/utils/checkForConfiguratorUpdates.js
  src/js/utils/common.js
  src/js/utils/generate_filename.js
  src/js/utils/isExportModeEnabled.js
  src/js/utils/showErrorDialog.js
  src/js/utils/updateTabList.js
  src/main.html
  src/tabs/presets/CliEngine.js
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
  src/tabs/presets/PresetsRepoIndexed/PresetParser.js
  src/tabs/presets/presets.js
Labels: RN: FEATURE

#3248 Fix OSD jBox Modal
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3241 Fix OSD (HD) display overflow on Android
  locales/en/messages.json
  src/css/tabs/osd.less
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: UI

#3253 Enable dynamic notch warning
  locales/en/messages.json
  src/css/tabs/pid_tuning.less
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: BUGFIX

#3252 Add zoom option to make OSD big in small screens
  locales/en/messages.json
  src/css/tabs/osd.less
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: UI

#3265 Don't close on select cloud build options
  src/js/tabs/firmware_flasher.js
Labels: RN: UI

#3264 Remove debug mode
  src/js/tabs/onboard_logging.js
Labels: Cleanup

#3257 Rename ExpressLRS "passphrase" to "binding phrase"
  locales/en/messages.json
  src/css/tabs/receiver.less
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: REFACTOR

#3263 Remove fetch for wiki
  src/js/gui.js
Labels: Cleanup

#3270 feat: use `three` as module
  .eslintrc.js
  src/js/main.js
  src/js/model.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
  src/main.html
Labels: dependencies

#3268 Remove deprecated features
  locales/en/messages.json
  src/js/Features.js
Labels: RN: BUGFIX

#3271 remove `object-hash` and `lru_map`
  .eslintrc.js
  package.json
  src/js/serial_backend.js
  src/main.html
  yarn.lock
Labels: Tested, dependencies

#3274 Improve debugging of MSP code
  src/js/Analytics.js
  src/js/msp/MSPHelper.js
Labels: enhancement

#3272 feat: use latest d3 version from npm
  .eslintrc.js
  libraries/d3.min.js
  package.json
  src/js/main.js
  src/js/tabs/motors.js
  src/js/tabs/receiver.js
  src/js/tabs/sensors.js
  src/main.html
  yarn.lock
Labels: dependencies

#3275 Update Wiki URL
  src/js/gui.js
Labels: Cleanup

#3276 recieverTab: lexcical sorted rxMode
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: UI

#3277 vtxTab: lexcical sort vtx_band
  src/js/tabs/vtx.js
Labels: Tested, RN: UI

#3284 fix CheckRunTimeError
  src/js/serial.js
  src/js/utils/common.js
Labels: RN: BUGFIX

#3280 Version bump in preparation for release
  package.json
Labels: Don't merge, RN: BUILD SYSTEM

#3259 Artery AT32F435/7 DFU and VCP support
  src/js/port_handler.js
  src/js/protocols/stm32usbdfu.js
  src/js/serial.js
Labels: Don't merge, RN: IMPROVEMENT

#3230 Add Octo X8 plus model
  src/js/model.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3287 OSD select sort
  src/js/tabs/osd.js
Labels: RN: UI

#3296 feat: drop jquery debounce for local implementation
  libraries/jquery.ba-throttle-debounce.min.js
  package.json
  src/js/tabs/osd.js
  src/main.html
  yarn.lock
Labels: dependencies, RN: REFACTOR

#3298 Fix telemetry being disabled for protocols used outside of ports tab
  src/js/tabs/ports.js
Labels: RN: BUGFIX

#3294 Fix links
  locales/en/messages.json
  src/js/VirtualFC.js
  src/tabs/adjustments.html
  src/tabs/auxiliary.html
  src/tabs/configuration.html
  src/tabs/failsafe.html
  src/tabs/firmware_flasher.html
  src/tabs/gps.html
  src/tabs/led_strip.html
  src/tabs/logging.html
  src/tabs/motors.html
  src/tabs/onboard_logging.html
  src/tabs/pid_tuning.html
  src/tabs/ports.html
  src/tabs/presets/presets.html
  src/tabs/receiver.html
  src/tabs/sensors.html
  src/tabs/transponder.html
Labels: Cleanup
