Repository betaflight/betaflight-configurator, pull requests merged in 2023-08, with the labels that each got.

#3538 Fix VTX ready status
  src/js/tabs/vtx.js
  src/tabs/vtx.html
Labels: RN: BUGFIX

#3527 GPS updates
  src/css/tabs/gps.less
  src/js/tabs/gps.js
  src/js/tabs/onboard_logging.js
Labels: Cleanup, RN: UI

#3537 Fix wiki
  src/js/tabs/firmware_flasher.js
  src/js/utils/common.js
Labels: RN: UI

#3539 feat: add sensor status vue component
  src/components/sensor-status/SensorStatus.stories.js
  src/components/sensor-status/SensorStatus.vue
Labels: RN: UI

#3544 Fix gps_rescue_min_dth
  src/js/tabs/failsafe.js
Labels: RN: BUGFIX

#3531 Add LED strip sliders
  locales/en/messages.json
  src/css/tabs/led_strip.less
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3548 Revert "Add LED strip sliders"
  locales/en/messages.json
  src/css/tabs/led_strip.less
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: Ready to Merge

#3555 GH action readme
  README.md
Labels: Housekeeping

#3500 Disable search in multiple select field for Other Options field when not selected
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3557 refactor: MSP binding to `this`
  src/js/msp.js
Labels: Tested, RN: REFACTOR

#3559 Axis Logo Update
  src/images/sponsors/Axisflying_dark.svg
  src/images/sponsors/Axisflying_light.svg
Labels: RN: UI

#3543 feat: added port picker vue component
  src/components/port-picker/FirmwareVirtualOption.stories.js
  src/components/port-picker/FirmwareVirtualOption.vue
  src/components/port-picker/PortOverrideOption.stories.js
  src/components/port-picker/PortOverrideOption.vue
  src/components/port-picker/PortsInput.stories.js
  src/components/port-picker/PortsInput.vue
Labels: RN: UI

#3554 Fix GPS Rescue parameters confusion
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/tabs/failsafe.html
Labels: Needs coordination with betaflight, RN: BUGFIX

#3292 Feat/vite build
  gulpfile.js
  package.json
  src/index.html
  src/js/browserMain.js
  src/js/main.js
  src/js/mdns_discovery.js
  src/js/msp.js
  src/js/port_handler.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/serial_devices.js
  src/js/tabs/receiver_msp.js
  src/js/webSerial.js
  vite.config.js
  yarn.lock
Labels: RN: BUILD SYSTEM
