Repository betaflight/betaflight-configurator, pull requests merged in 2023-05, with the labels that each got.

#3435 Fix missing tooltip messages
  locales/en/messages.json
  src/tabs/auxiliary.html
Labels: RN: BUGFIX

#3415 Improve MSP handling
  src/js/msp.js
  src/js/msp/MSPHelper.js
  src/js/protocols/stm32.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/ports.js
  src/js/tabs/power.js
  src/js/tabs/servos.js
  src/js/tabs/vtx.js
Labels: Testing Required, RN: IMPROVEMENT

#3442 Fix mixer
  src/js/model.js
Labels: RN: BUGFIX

#3439 Add DSHOT_TELEMETRY_COUNTS debug mode
  src/js/tabs/onboard_logging.js
Labels: RN: IMPROVEMENT

#3445 Fix: tooltip
  locales/en/messages.json
Labels: RN: BUGFIX

#3438 Fix: arm status [icon]
  src/css/main.less
  src/js/sensor_helpers.js
  src/js/serial_backend.js
  src/js/tabs/motors.js
  src/js/tabs/setup.js
Labels: RN: BUGFIX

#3444 Refactor: writeConfiguration
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/auxiliary.js
  src/js/tabs/configuration.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/led_strip.js
  src/js/tabs/motors.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/power.js
  src/js/tabs/receiver.js
  src/js/tabs/transponder.js
  src/js/tabs/vtx.js
Labels: RN: REFACTOR

#3449 Fix invalid version
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: Testing Required, RN: BUGFIX

#3465 Bump multipleSelect to 1.6.0
  package.json
  yarn.lock
Labels: Rebase Required, dependencies

#3462 Downgrade nw-builder to version 3.8.3
  package.json
  yarn.lock
Labels: fixes broken build
