Repository betaflight/betaflight-configurator, pull requests merged in 2023-10, with the labels that each got.

#3605 Increase the time between status requests (increasing overall timeout)
  src/js/tabs/firmware_flasher.js
Labels: RN: IMPROVEMENT

#3606 Adding version details to the PWA
  .eslintrc.js
  src/js/main.js
  vite.config.js
Labels: Housekeeping

#3615 Fix missing OSD stats
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3617 Fix missing stat desc
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Tested, RN: BUGFIX
