Repository betaflight/betaflight-configurator, pull requests merged in 2023-07, with the labels that each got.

#3491 Concat longitude and latitude and add location url on Setup tab
  locales/en/messages.json
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: UI

#3492 Add debug disable field for unfiltered gyro
  src/js/tabs/onboard_logging.js
Labels: RN: IMPROVEMENT

#3505 Enable video transmitter tab
  src/js/Features.js
  src/js/gui.js
  src/js/serial_backend.js
  src/js/tabs/ports.js
  src/js/utils/updateTabList.js
Labels: Tested, RN: BUGFIX

#3509 Create data flash vue component
  src/components/data-flash/DataFlash.stories.js
  src/components/data-flash/DataFlash.vue
Labels: RN: UI

#3507 Cleanup old code
  src/js/tabs/osd.js
Labels: Cleanup

#3506 Fix missing GPS Laptimer OSD elements
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3511 Bump NWJS to v0.77.0
  gulpfile.js
Labels: dependencies

#3515 Fix intermittent connect failure
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/ports.js
Labels: RN: BUGFIX

#3512 Revert hiding VTX tab
  src/js/Features.js
  src/js/gui.js
  src/js/utils/updateTabList.js
Labels: Cleanup, Ready to Merge

#3525 Fix GPS waiting info margin
  src/css/tabs/gps.less
  src/js/tabs/gps.js
Labels: RN: UI

#3522 Add all 8 debug values in sensors tab and only show active debugs
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/sensors.js
  src/tabs/sensors.html
Labels: RN: IMPROVEMENT

#3529 Add Ukrainian translation
  .github/workflows/translations-pr.yml
  assets/windows/installer.iss
  locales/en/messages.json
  locales/uk/messages.json
  src/js/localization.js
Labels: Translation

#3519 AUX modes updated in help tips and virtuelFC, also sort of LinkedTo option list at Mode tab
  locales/en/messages.json
  src/js/VirtualFC.js
  src/js/tabs/auxiliary.js
Labels: Tested, RN: UI

#3516 GPS tab with same design for lat / lon as on Setup tab
  locales/en/messages.json
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: UI

#3533 Quad status
  src/components/quad-status/BottomStatusIcons.stories.js
  src/components/quad-status/BottomStatusIcons.vue
Labels: RN: UI
