Repository betaflight/betaflight-configurator, pull requests merged in 2023-11, with the labels that each got.

#3620 Fix virtual disconnect
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3621 Sort and translate font name at OSD tab
  locales/en/messages.json
  src/js/tabs/osd.js
  src/tabs/osd.html
Labels: RN: UI

#3611 Enable GPS Rescue UI if used as a mode
  src/js/tabs/failsafe.js
Labels: RN: IMPROVEMENT

#3551 Indicate configuration saving on LED Strip tab
  locales/en/messages.json
  src/js/tabs/led_strip.js
  src/js/tabs/vtx.js
Labels: RN: UI

#3623 Servo tab: Rearrange mid, min, max and translate Rate:
  locales/en/messages.json
  src/js/tabs/servos.js
  src/tabs/servos.html
Labels: RN: UI

#3624 Fix/improve dynamicIdle hidding
  locales/en/messages.json
  src/js/tabs/motors.js
  src/tabs/motors.html
Labels: RN: IMPROVEMENT

#3622 Translate labels at reciever signal graph
  locales/en/messages.json
  src/tabs/receiver.html
Labels: RN: UI

#3626 Fix button behaviour
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3593 Show magADC values without re-scaling in Sensors Tab
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/sensors.js
  src/tabs/sensors.html
Labels: Ready to Merge, RN: IMPROVEMENT

#3625 Show idleMinRpm on motor tab (active profile)
  locales/en/messages.json
  src/css/main.less
  src/js/tabs/motors.js
  src/tabs/motors.html
Labels: RN: IMPROVEMENT

#3634 motor direction tools: gui_log the direction clicked
  src/components/EscDshotDirection/EscDshotDirectionMotorDriver.js
Labels: RN: IMPROVEMENT

#3637 Append craftname
  src/js/tabs/firmware_flasher.js
  src/js/utils/generate_filename.js
Labels: Tested, RN: IMPROVEMENT

#3640 Fix sensor status calls
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3644 Add MSP2_SENSOR_CONFIG_ACTIVE message
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#3646 Add missing debugmodes and fields
  src/js/debug.js
  src/js/tabs/setup.js
Labels: RN: IMPROVEMENT

#3648 Fix receiver tooltip
  src/css/tabs/receiver.less
  src/js/Features.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: BUGFIX

#3650 Translate hardware status info
  locales/en/messages.json
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: UI, RN: TRANSLATION
