Repository betaflight/betaflight-configurator, pull requests merged in 2023-04, with the labels that each got.

#3398 Update android build info in README.md
  README.md
Labels: Housekeeping

#3390 Cleanup + led overlay expansion
  src/css/tabs/led_strip.less
  src/js/msp/MSPHelper.js
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: Cleanup, Needs coordination with betaflight, RN: IMPROVEMENT

#3402 Add more localization on setup tab
  locales/en/messages.json
  src/tabs/setup.html
Labels: RN: UI

#3403 Show CPU core temp on Setup tab
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3405 Fix full chip erase
  src/js/tabs/firmware_flasher.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3400 align alignDisarmFlagElements
  src/js/tabs/setup.js
Labels: RN: REFACTOR

#3410 Add sensor / range finder information at Setup tab
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/setup.js
Labels: Tested, RN: IMPROVEMENT

#3397 Fix battery status and optimize and fix status pull
  src/js/fc.js
  src/js/gui.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/adjustments.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/motors.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
  src/js/tabs/setup.js
Labels: Ready to Merge, RN: BUGFIX

#3412 Move mDNS initialization
  src/js/mdns_discovery.js
  src/js/port_handler.js
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3413 More feature tip at Configuration tab
  locales/en/messages.json
  src/js/Features.js
Labels: RN: UI

#3414 Show sonar altitude, if sensor exist
  locales/en/messages.json
  src/js/msp/MSPCodes.js
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#3421 Add a few unit tests for MSP protocol
  test/js/msp.test.js
Labels: tests

#3427 Fix no buildkey
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3425 Add a few unit tests for MspHelper class
  src/js/msp.js
  src/js/msp/MSPHelper.js
  test/js/msp/MSPHelper.test.js
Labels: Tested, RN: REFACTOR, tests

#3428 Clarify the usage of crash flip arrow
  locales/en/messages.json
Labels: RN: IMPROVEMENT

#3422 Color for vtx ready status
  locales/en/messages.json
  src/css/main.less
  src/js/tabs/gps.js
  src/js/tabs/setup.js
  src/js/tabs/vtx.js
  src/tabs/gps.html
  src/tabs/setup.html
  src/tabs/vtx.html
Labels: RN: UI

#3430 Add help to modes at Mode tab
  locales/en/messages.json
  src/js/tabs/auxiliary.js
  src/tabs/auxiliary.html
Labels: RN: UI
