Repository betaflight/betaflight-configurator, pull requests merged in 2023-12, with the labels that each got.

#3641 Fix tab switch
  src/js/gui.js
Labels: RN: BUGFIX

#3642 Fix IMU sensor refresh rate selection
  src/js/tabs/sensors.js
  src/tabs/sensors.html
Labels: Ready to Merge, RN: BUGFIX

#3647 Fix weird character
  src/js/tabs/auxiliary.js
Labels: Cleanup

#3652 Fix rev
  src/js/main.js
  vite.config.js
Labels: RN: BUGFIX

#3609 Add Link Quality alarm value to the OSD tab
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#3547 fixed accel scaling in motors tab
  src/js/msp/MSPHelper.js
Labels: Needs coordination with betaflight, RN: BUGFIX

#3656 Add LSM6DSV16X
  src/js/tabs/setup.js
Labels: Ready to Merge, RN: IMPROVEMENT

#3661 Fix flash button color
  src/js/serial_backend.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3660 Update arming disable flag
  src/js/tabs/setup.js
Labels: Cleanup, Ready to Merge

#3662 Fix readonly field
  src/css/tabs/motors.less
Labels: Ready to Merge, RN: UI

#3658 Fix macos build
  .github/workflows/ci.yml
Labels: Housekeeping

#3655 Add EZLANDING debug
  src/js/debug.js
Labels: Needs coordination with betaflight, RN: FEATURE

#3663 Use attitude heading
  locales/en/messages.json
  src/js/tabs/gps.js
  src/js/tabs/map.js
Labels: Ready to Merge, Tested, RN: BUGFIX, RN: UI

#3667 Fix autodetect
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: BUGFIX

#3668 Rotate map icon instead of view
  src/js/tabs/map.js
Labels: Ready to Merge, Tested, RN: IMPROVEMENT

#3669 Fix heading calculation
  src/js/tabs/gps.js
Labels: RN: BUGFIX

#3671 Add MSP support for led profile and status
  src/js/fc.js
  src/js/msp/MSPHelper.js
Labels: Tested, RN: IMPROVEMENT

#3670 Defer URL check
  locales/en/messages.json
  src/css/tabs/firmware_flasher.less
  src/js/gui.js
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: IMPROVEMENT

#3672 Fix message
  locales/en/messages.json
Labels: RN: BUGFIX

#3597 feat: only use rollup output for build
  gulpfile.js
  package.json
  yarn.lock
Labels: Tested, Housekeeping

#3674 Update debug-scheduler-determinism
  src/js/debug.js
Labels: RN: IMPROVEMENT

#3673 Update nodejs
  .nvmrc
  package.json
  yarn.lock
Labels: Tested, dependencies, RN: BUILD SYSTEM

#3676 Revive MSP message for mag declination
  locales/en/messages.json
  src/js/backup_restore.js
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#3677 Fix translated messages
  locales/en/messages.json
  src/js/tabs/failsafe.js
Labels: RN: BUGFIX

#3678 Update @fortawesome/fontawesome-free
  package.json
  src/main.html
  yarn.lock
Labels: dependencies

#3679 Fix stylesheet import
  src/main.html
Labels: RN: BUGFIX

#3680 Fix usage of cloud build options
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: BUGFIX

#3682 Fix: maps and `dist/dist/dist` builds
  gulpfile.js
Labels: Tested, RN: BUGFIX

#3683 Feat/npm ol
  gulpfile.js
  libraries/openlayers/ol.css
  libraries/openlayers/ol.css.map
  libraries/openlayers/ol.js
  libraries/openlayers/ol.js.map
  package.json
  src/css/tabs/gps.less
  src/js/tabs/gps.js
  src/js/tabs/map.js
  src/tabs/gps.html
  src/tabs/map.html
  yarn.lock
Labels: Tested, dependencies

#3684 chore: add debug config for vscode
  .gitignore
  .vscode/launch.json
  package.json
Labels: enhancement

#3688 fix: ol maps css loading on web
  gulpfile.js
Labels: Cleanup

#3687 fix: bonjour conditional loading
  src/css/tabs/gps.less
  src/js/mdns_discovery.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3685 Add satellite layer and show map on latlon values
  locales/en/messages.json
  src/css/tabs/gps.less
  src/js/tabs/gps.js
  src/js/tabs/map.js
  src/tabs/gps.html
Labels: Ready to Merge, Tested, RN: IMPROVEMENT

#3692 Revert "Add MSP support for led profile and status (#3671)"
  src/js/fc.js
  src/js/msp/MSPHelper.js
Labels: Cleanup, Ready to Merge, Tested

#3693 Fix buildOptions for DFU mode
  src/js/tabs/firmware_flasher.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3689 Add MSP2_UBLOX_REQUEST_SV_INFO
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/gps.js
Labels: Tested, RN: BUGFIX

#3698 Remove SatInfo request
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/tabs/gps.js
Labels: Cleanup

#3697 Adding sponsor tile to the landing page.
  src/css/tabs/landing.less
  src/js/BuildApi.js
  src/js/Sponsor.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/landing.js
  src/tabs/landing.html
Labels: RN: IMPROVEMENT

#3706 fix: msp receiver emulator
  src/js/tabs/receiver_msp.js
  src/tabs/receiver_msp.html
Labels: RN: BUGFIX

#3708 Fix Android
  gulpfile.js
Labels: RN: BUGFIX

#3702 Respect language & nationalities
  locales/en/messages.json
Labels: RN: BUGFIX

#3709 Fix fontawesome stylesheet for cordova
  src/main_cordova.html
Labels: RN: BUGFIX

#3714 D3 - Version is no longer an available property - removing.
  src/js/main.js
Labels: Cleanup

#3716 Fix/build output layout
  gulpfile.js
  src/index.html
  src/js/main.js
Labels: RN: BUGFIX

#3715 Set the rollupReplace default param - removes warning message.
  gulpfile.js
Labels: Cleanup
