Repository betaflight/betaflight-configurator, pull requests merged in 2023-03, with the labels that each got.

#3364 [10.9-maintenance] Fix: vtx tab -> vtx type (#3353)
  src/js/utils/VtxDeviceStatus/Rtc6705DeviceStatus.js
  src/js/utils/VtxDeviceStatus/SmartAudioDeviceStatus.js
  src/js/utils/VtxDeviceStatus/TrampDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatusFactory.js
  src/js/utils/VtxDeviceStatus/VtxMspDeviceStatus.js
Labels: RN: BUGFIX

#3352 Option to automatically open DevTools
  locales/en/messages.json
  src/js/data_storage.js
  src/js/main.js
  src/js/tabs/options.js
  src/tabs/options.html
Labels: RN: IMPROVEMENT

#3363 Select blackbox debug fields
  locales/en/messages.json
  src/css/tabs/onboard_logging.less
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/onboard_logging.js
  src/tabs/onboard_logging.html
Labels: RN: IMPROVEMENT

#3355 Display heading on GPS Tab
  locales/en/messages.json
  src/js/VirtualFC.js
  src/js/fc.js
  src/js/tabs/gps.js
  src/js/tabs/map.js
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#3358 Remove setting of client version in the cloud build request
  src/js/tabs/firmware_flasher.js
Labels: RN: BUILD SYSTEM

#3332 Expose Cloud Build Options and hide tabs and features
  locales/en/messages.json
  src/js/BuildApi.js
  src/js/Features.js
  src/js/data_storage.js
  src/js/fc.js
  src/js/gui.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/ports.js
  src/js/utils/updateTabList.js
  src/tabs/configuration.html
Labels: Testing Required, RN: IMPROVEMENT

#3377 GPS icon now reflect fix state
  src/css/main.less
  src/images/icons/sensor_sat_on_no_fix.png
  src/images/icons/sensor_sat_on_with_fix.png
  src/js/msp/MSPHelper.js
  src/js/sensor_helpers.js
  src/js/serial_backend.js
Labels: RN: UI

#3369 Firmware info on setup tab
  locales/en/messages.json
  src/css/main.less
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: UI

#3378 Fix gyro_hardware_lpf
  src/js/msp/MSPHelper.js
Labels: RN: BUGFIX

#3381 Change blackbox debug
  locales/en/messages.json
  src/css/tabs/onboard_logging.less
  src/js/tabs/onboard_logging.js
Labels: RN: UI

#3383 FIX: Adjusting setting of ajax default header as not being passed for version check
  src/js/main.js
Labels: RN: BUGFIX

#3384 Load available cloud build options when selecting the firmware version to build
  src/js/BuildApi.js
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: IMPROVEMENT

#3386 FIX: missing debug modes
  src/js/tabs/onboard_logging.js
Labels: RN: BUGFIX

#3391 Fix toggle switch margin in LED tab
  src/css/tabs/led_strip.less
Labels: RN: UI

#3382 FIX: feature ESC_SENSOR
  src/js/Features.js
  src/js/tabs/motors.js
Labels: Ready to Merge, Tested, RN: BUGFIX

#3394 Show logname on logging tab
  locales/en/messages.json
  src/js/tabs/logging.js
  src/tabs/logging.html
Labels: RN: UI

#3396 Fix max length of craft name and pilot name
  src/tabs/configuration.html
Labels: RN: BUGFIX
