Repository betaflight/betaflight-configurator, pull requests merged in 2023-02, with the labels that each got.

#3301 Simplify Expert Mode
  locales/en/messages.json
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/options.js
  src/tabs/firmware_flasher.html
  src/tabs/options.html
Labels: RN: IMPROVEMENT

#3279 refactor: drop bluebird dependency
  package.json
  src/js/tabs/cli.js
  src/js/tabs/osd.js
  src/main.html
  src/tabs/presets/CliEngine.js
  src/tabs/presets/PresetsRepoIndexed/PresetsRepoIndexed.js
  test/setup.js
  test/tabs/cli.test.js
  yarn.lock
Labels: dependencies

#3308 Patch VTX link and fix all remaining links
  locales/en/messages.json
Labels: Cleanup

#3313 Add FAILSAFE and GYRO_CALIBRATION debug modes
  src/js/tabs/onboard_logging.js
Labels: RN: IMPROVEMENT

#3312 Found two more links
  locales/en/messages.json
Labels: Cleanup

#3325 Fix presets loading
  src/tabs/presets/CliEngine.js
Labels: RN: BUGFIX

#3330 Fix Core Only toggle
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: BUGFIX

#3326 Move GPS configuration to GPS tab
  locales/en/messages.json
  src/css/tabs/configuration.less
  src/css/tabs/gps.less
  src/js/Features.js
  src/js/tabs/configuration.js
  src/js/tabs/gps.js
  src/tabs/configuration.html
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#3334 Update NW.js to 0.72.0
  gulpfile.js
Labels: dependencies

#3335 Updated the PR template (2)
  .github/pull_request_template.md
Labels: Housekeeping

#3337 Fix mDNS browser
  locales/en/messages.json
  src/js/port_handler.js
  src/js/tabs/options.js
  src/tabs/options.html
Labels: Ready to Merge, Tested, RN: BUGFIX

#3346 Simplified configurator version checking
  src/js/BuildApi.js
  src/js/release_checker.js
  src/js/utils/checkForConfiguratorUpdates.js
Labels: RN: IMPROVEMENT

#3349 Fix latest version check
  src/js/utils/checkForConfiguratorUpdates.js
Labels: RN: BUGFIX

#3348 replaceAll-workaround
  src/js/main.js
Labels: Tested, RN: BUGFIX

#3350 Extend submit support ID with problem description field
  locales/en/messages.json
  src/css/tabs/cli.less
  src/js/tabs/cli.js
  src/tabs/cli.html
Labels: RN: IMPROVEMENT

#3359 Fix css in gps tab
  src/css/tabs/gps.less
Labels: RN: UI

#3353 Fix: vtx tab -> vtx type
  src/js/utils/VtxDeviceStatus/Rtc6705DeviceStatus.js
  src/js/utils/VtxDeviceStatus/SmartAudioDeviceStatus.js
  src/js/utils/VtxDeviceStatus/TrampDeviceStatus.js
  src/js/utils/VtxDeviceStatus/VtxDeviceStatusFactory.js
  src/js/utils/VtxDeviceStatus/VtxMspDeviceStatus.js
Labels: RN: BUGFIX

#3362 Limit groundspeed in UI to 3m/s
  src/tabs/failsafe.html
Labels: RN: UI
