Repository betaflight/betaflight-configurator, pull requests merged in 2024-06, with the labels that each got.

#3993 Fix noselection and not closing dfu after flashing
  src/components/port-picker/PortsInput.vue
  src/js/protocols/webusbdfu.js
  src/js/serial_backend.js
Labels: RN: BUGFIX, PWA

#4004 Move hex_parser.js worker to an async function in a module
  src/js/tabs/firmware_flasher.js
  src/js/workers/hex_parser.js
Labels: RN: BUGFIX, PWA

#3996 Add web API support for flashing
  src/js/msp/MSPConnector.js
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/protocols/stm32usbdfu.js
  src/js/protocols/webstm32.js
  src/js/tabs/firmware_flasher.js
  src/js/usb_shim.js
Labels: Tested, RN: REFACTOR, PWA

#4003 Define default values for options in the port handler
  src/js/port_handler.js
Labels: RN: BUGFIX, PWA

#4005 Refactor auto-backup in flashing tab for PWA
  src/js/tabs/firmware_flasher.js
  src/js/utils/AutoBackup.js
Labels: RN: REFACTOR, PWA

#4006 Extract auto-detect from firmware flasher for PWA
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/js/utils/AutoDetect.js
  src/js/webSerial.js
Labels: RN: REFACTOR, PWA

#4009 Increment minimal supported API to 1_44 (firmware 4.3) (2/4)
  locales/en/messages.json
  src/js/tabs/motors.js
Labels: RN: REFACTOR

#4010 Increment minimal supported API to 1_44 (firmware 4.3) (3/4)
  locales/en/messages.json
  src/js/TuningSliders.js
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: REFACTOR

#4007 Remove experimental backup and restore
  locales/en/messages.json
  src/components/port-picker/FirmwareVirtualOption.vue
  src/js/backup_restore.js
  src/js/data_storage.js
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: REFACTOR

#4011 Increment minimal supported API to 1_44 (firmware 4.3) (4/4)
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/js/Features.js
  src/js/RateCurve.js
  src/js/data_storage.js
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/protocols/webstm32.js
  src/js/tabs/failsafe.js
  src/js/tabs/gps.js
  src/js/tabs/setup.js
  src/js/utils/AutoDetect.js
  src/js/utils/EscProtocols.js
Labels: RN: REFACTOR

#4016 Update messages.json typo fix
  locales/en/messages.json
Labels: RN: BUGFIX

#4015 Use object-fit for sponsor logos
  src/css/main.less
Labels: RN: UI

#4013 Fix dual permission dialog when flashing
  src/js/port_handler.js
  src/js/protocols/webstm32.js
Labels: RN: BUGFIX

#4012 Cleaning up leftovers
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/receiver.js
  src/tabs/motors.html
  src/tabs/receiver.html
Labels: Cleanup

#4014 Fix showDialogVerifyBoard
  src/js/gui.js
  src/js/port_handler.js
  src/js/protocols/webstm32.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/osd.js
  src/js/tabs/receiver.js
  src/js/utils/AutoDetect.js
  src/tabs/firmware_flasher.html
Labels: Cleanup, PWA

#4018 Fix crashing of presets and vtx tab
  src/js/gui.js
  src/js/main.js
  src/js/utils/checkForConfiguratorUpdates.js
Labels: RN: BUGFIX, PWA

#4019 Fix board name in logo and status bar
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
Labels: RN: BUGFIX

#4020 Add RSSI dBm alarm configurable in the OSD tab
  locales/en/messages.json
  src/js/data_storage.js
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight

#4026 Fix port selection blank under some situations
  src/js/port_handler.js
Labels: RN: BUGFIX, PWA

#4029 Fix tethered logging under PWA
  src/js/FileSystem.js
  src/js/tabs/logging.js
  src/tabs/logging.html
Labels: RN: REFACTOR, PWA

#4030 Fix disarm flag elements
  src/js/tabs/setup.js
Labels: Cleanup

#4022 Add CPU LOAD warning to the OSD tab (#4021)
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: RN: FEATURE

#4039 Show all serial devices option PWA
  src/components/status-bar/ReadingStat.vue
  src/js/port_handler.js
  src/js/tabs/options.js
  src/js/webSerial.js
Labels: build system improvement, PWA

#4033 Fix autobackup
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/utils/AutoBackup.js
Labels: RN: BUGFIX, PWA

#4042 Some adjustments to the VTX tab UI
  src/css/main.less
  src/tabs/vtx.html
Labels: RN: UI

#4043 Fix UI toolbar buttons at tethered logging
  src/css/tabs/logging.less
  src/tabs/logging.html
Labels: RN: UI

#4040 Fix some UI glitches in servos tab
  src/css/main.less
  src/css/tabs/servos.less
  src/tabs/servos.html
Labels: RN: UI

#4041 Remove space for hidden buttons in the toolbar
  src/css/main.less
Labels: RN: UI

#4044 Update debug
  src/css/select2_custom.less
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4045 Several little UI adjustments
  src/css/tabs/configuration.less
  src/css/tabs/firmware_flasher.less
  src/css/tabs/pid_tuning.less
  src/css/tabs/sensors.less
  src/css/tabs/setup.less
  src/css/tabs/static_tab.less
  src/tabs/pid_tuning.html
  src/tabs/presets/presets.less
  src/tabs/sensors.html
Labels: RN: UI

#4047 Fix message
  locales/en/messages.json
Labels: Cleanup

#4046 Request permission before connect in USB flashing
  src/js/protocols/webstm32.js
  src/js/protocols/webusbdfu.js
  src/js/tabs/firmware_flasher.js
Labels: RN: REFACTOR, PWA

#4049 Fix CLI autocomplete background color
  src/css/tabs/cli.less
Labels: RN: UI

#4048 Auto flashing without asking permissions if possible
  src/js/protocols/webstm32.js
  src/js/tabs/firmware_flasher.js
Labels: Testing Required, RN: REFACTOR, PWA

#4035 Move analytics to its own domain and capture host
  src/js/Analytics.js
  src/js/BuildApi.js
Labels: Housekeeping

#4036 10.10-maintenance: Move analytics to its own domain and capture host
  src/js/Analytics.js
  src/js/BuildApi.js
Labels: Housekeeping

#4054 Style: Fix jBox tooltip colors
  src/css/main.less
Labels: RN: UI

#4056 Make msc-not-support expert only
  src/js/tabs/onboard_logging.js
Labels: RN: UI

#4053 Fix servo tab not shown
  src/js/utils/updateTabList.js
Labels: RN: BUGFIX

#4025 Disable vbat-sagcompensation if voltage source is not ADC
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#4060 Adjust RX Plot graph elements
  src/css/tabs/receiver.less
  src/tabs/receiver.html
Labels: RN: UI

#4061 Fix missing dmin gain and advance
  src/tabs/pid_tuning.html
Labels: Cleanup

#4059 Change Vite register type to prompt for PWA
  locales/en/messages.json
  src/js/browserMain.js
  vite.config.js
Labels: RN: IMPROVEMENT

#4062 Fix disabled state of autodetect button
  src/css/tabs/firmware_flasher.less
  src/tabs/firmware_flasher.html
Labels: Cleanup, RN: UI

#4063 Fix firmware flasher tab toolbar
  src/css/tabs/firmware_flasher.less
Labels: RN: UI

#4064 Upgrade packages to latest versions in yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#4066 Fix presets UI buttons bar
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.less
  src/tabs/presets/presets.less
Labels: RN: UI

#4067 Fix button toolbar in motors and modes tabs
  src/css/tabs/auxiliary.less
  src/css/tabs/motors.less
Labels: RN: UI

#4052 Add altitude variant
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with betaflight, RN: IMPROVEMENT

#4068 Use diff
  src/js/utils/AutoBackup.js
Labels: Cleanup

#4024 Add bluetooth support
  locales/en/messages.json
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/js/msp.js
  src/js/port_handler.js
  src/js/protocols/bluetooth.js
  src/js/serial_backend.js
  src/js/serial_shim.js
  src/js/webSerial.js
Labels: RN: FEATURE, PWA

#4071 [github workflow] auto-close PR's with branch named 'master'
  .github/workflows/auto-close.yml
Labels: Housekeeping

#3955 Add capacitor android
  README.md
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/betaflight/configurator/MainActivity.java
  android/app/src/main/res/drawable-land-hdpi/splash.png
  android/app/src/main/res/drawable-land-mdpi/splash.png
  android/app/src/main/res/drawable-land-xhdpi/splash.png
  android/app/src/main/res/drawable-land-xxhdpi/splash.png
  android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  android/app/src/main/res/drawable-port-hdpi/splash.png
  android/app/src/main/res/drawable-port-mdpi/splash.png
  android/app/src/main/res/drawable-port-xhdpi/splash.png
  android/app/src/main/res/drawable-port-xxhdpi/splash.png
  android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/xml/file_paths.xml
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  android/variables.gradle
  capacitor.config.json
  package.json
  yarn.lock
Labels: RN: IMPROVEMENT, PWA

#4069 Add APM32 device support
  src/js/serial_devices.js
Labels: RN: IMPROVEMENT

#4072 CLI Text dark font on dark background fix.
  src/css/tabs/cli.less
Labels: RN: UI

#4073 Aesthetic CLI dropdown menu
  src/css/tabs/cli.less
Labels: RN: UI
