Repository betaflight/betaflight-configurator, pull requests merged in 2024-11, with the labels that each got.

#4232 substitue `aircraft` for `craft`, `drone`, or `quad`
  locales/en/messages.json
Labels: RN: REFACTOR

#4244 Add STMicroelectronics STLink Virtual COM Port
  src/js/serial_devices.js
Labels: RN: IMPROVEMENT

#4241 Fix gps color
  src/js/tabs/gps.js
Labels: RN: UI

#4249 Only show first line of commit message
  src/js/tabs/firmware_flasher.js
Labels: RN: IMPROVEMENT

#4250 Fix sponsor loading
  src/js/Sponsor.js
  src/js/gui.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#4251 Enforce OSD option
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: IMPROVEMENT

#4255 Update README.md
  README.md
Labels: Housekeeping

#4256 Update README.md
  README.md
Labels: Housekeeping

#4257 Fix vtx tab presentation
  src/css/tabs/vtx.less
  src/tabs/vtx.html
Labels: RN: UI

#4248 Attitude field added to blackbox fields list
  src/js/debug.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT

#4211 Update TPA debug (Wing)
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4260 Add Gimbal debug
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4261 Add WING_SETPOINT debug
  src/js/debug.js
Labels: RN: IMPROVEMENT
