Repository betaflight/betaflight-configurator, pull requests merged in 2024-03, with the labels that each got.

#3824 Fix lost context
  src/js/model.js
  src/js/tabs/pid_tuning.js
  src/js/tabs/receiver.js
Labels: RN: BUGFIX

#3827 Only update unused modes when needed
  src/js/tabs/auxiliary.js
Labels: RN: BUGFIX

#3825 Fix getContext
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#3752 [Chore] apply lexical scoping to stm32usbdfu
  src/js/protocols/stm32usbdfu.js
Labels: Tested, RN: REFACTOR

#3834 Improve sponsors tab layout
  src/css/main.less
Labels: RN: UI

#3840 [github actions] fix release assets upload
  .github/workflows/build-release.yml
  .github/workflows/release.yml
Labels: Housekeeping

#3845 fix testing-failsafe link
  locales/en/messages.json
Labels: RN: UI

#3846 TPA clarification - % and μs
  locales/en/messages.json
Labels: RN: UI

#3850 Fix missing message
  src/js/tabs/setup.js
Labels: Cleanup

#3851 TPA Clarification
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: UI

#3858 Fix flash on connect
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3863 feat: add netlify config file
  netlify.toml
Labels: Housekeeping

#3861 Update tooltip
  locales/en/messages.json
Labels: RN: UI
