Repository betaflight/betaflight-configurator, pull requests merged in 2024-01, with the labels that each got.

#3713 Fix language selection
  src/js/tabs/landing.js
Labels: RN: BUGFIX

#3722 Fix Android icons
  gulpfile.js
Labels: Tested, RN: UI

#3718 feat: add basic offline pwa support
  package.json
  src/images/pwa/apple-touch-icon.png
  src/images/pwa/favicon.ico
  src/images/pwa/pwa-192-192.png
  src/images/pwa/pwa-512-512.png
  src/index.html
  src/js/browserMain.js
  vite.config.js
  yarn.lock
Labels: RN: IMPROVEMENT

#3720 Add missing MSP_SET_OSD_CANVAS support
  src/js/msp/MSPHelper.js
  src/js/tabs/osd.js
Labels: RN: IMPROVEMENT

#3721 Fix sponsor background on landing page
  src/css/tabs/landing.less
Labels: RN: UI

#3725 Update wiki links in locales
  locales/en/messages.json
Labels: Cleanup

#3728 Revert "Add missing MSP_SET_OSD_CANVAS support"
  src/js/msp/MSPHelper.js
  src/js/tabs/osd.js
Labels: Cleanup, Ready to Merge

#3712 Relax MSP timeout
  src/js/msp.js
Labels: For Discussion

#3729 Updating analytics to use build server
  package.json
  src/js/Analytics.js
  src/js/BuildApi.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/onboard_logging.js
  yarn.lock
Labels: Cleanup

#3701 Enable erase_chip by default
  src/js/ConfigStorage.js
  src/js/main.js
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3731 Fix sonar to reflect datastruct has no default
  src/js/tabs/setup.js
Labels: Cleanup

#3732 More virtual information
  src/js/VirtualFC.js
Labels: RN: IMPROVEMENT

#3726 Hide telemetry protocols for CRSF, FPORT and GHST
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
Labels: RN: UI

#3733 Background pattern on full landing tab
  src/css/tabs/landing.less
Labels: RN: UI

#3734 fix landing page dark theme Background pattern
  src/css/dark-theme.less
Labels: Cleanup

#3739 Minor Facelift for Landing Page (Dark Mode)
  src/css/dark-theme.less
  src/css/tabs/landing.less
  src/images/bf_logo_black.svg
  src/images/bf_logo_white.svg
  src/images/pattern_dark.png
  src/images/pattern_light.png
Labels: RN: UI

#3738 Update messages.json
  locales/en/messages.json
Labels: Cleanup

#3741 Migrate hub to gh
  .github/workflows/build-release.yml
Labels: Housekeeping

#3736 Improved build request management
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/en/messages.json
  locales/es/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/uk/messages.json
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: IMPROVEMENT, RN: BUILD SYSTEM

#3737 Fix mag declination css for dark mode
  src/css/tabs/gps.less
Labels: Cleanup

#3745 Prevent detection when busy
  src/js/port_handler.js
  src/js/tabs/firmware_flasher.js
Labels: Testing Required, RN: BUGFIX

#3750 Improved messaging if build request fails
  locales/en/messages.json
  src/js/tabs/firmware_flasher.js
Labels: RN: UI

#3758 Fix isWeb usage and missing callback
  src/js/msp.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: Cleanup

#3763 Dogcom logo: light and dark theme
  src/images/sponsors/dogcom.svg
  src/images/sponsors/dogcom_dark.svg
  src/images/sponsors/dogcom_light.svg
Labels: Don't merge, RN: UI

#3760 Update tooltip for ESC Temp
  locales/en/messages.json
Labels: RN: UI

#3772 Ensure there is sufficient space between sponsor logos
  src/css/main.less
Labels: Housekeeping

#3771 Increased consistency with tracking parameters captured.
  src/js/CliAutoComplete.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/vtx.js
Labels: Housekeeping

#3753 Improve messaging on motors tab
  locales/en/messages.json
  src/css/tabs/motors.less
Labels: RN: UI

#3778 Update receiver.html
  src/tabs/receiver.html
Labels: RN: UI

#3747 Cleanup more F3 code
  src/js/boards.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/ports.js
Labels: Cleanup
