Repository betaflight/betaflight-configurator, pull requests merged in 2024-12, with the labels that each got.

#4265 FIx missing crashflip arming disable flag
  src/js/tabs/setup.js
Labels: RN: BUGFIX

#4268 Resolved attitude log disabled flag enum position issue
  src/js/debug.js
Labels: RN: BUGFIX

#4267 Show SDC in DataFlash component
  src/components/data-flash/DataFlash.vue
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/update_dataflash_global.js
Labels: RN: IMPROVEMENT

#4270 Update messages
  locales/en/messages.json
Labels: RN: IMPROVEMENT

#4271 add Servo debug disable field
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4273 Adjust 3D boxmode
  locales/en/messages.json
Labels: RN: REFACTOR

#4277 Style: Fix contrast issues on dark mode
  src/css/dark-theme.less
  src/css/main.less
  src/js/tabs/pid_tuning.js
  src/tabs/auxiliary.html
Labels: RN: UI

#4281 Add custom osd msg support from external device
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT

#4284 Add AUTOPILOT_POSITION and OPTICALFLOW debug modes
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4105 Added LED Brightness Adjust
  locales/en/messages.json
  src/js/tabs/adjustments.js
Labels: RN: FEATURE

#4283 Adding support for UART0
  src/js/tabs/ports.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT

#4285 Fix for preset options that are outside of any groups
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
Labels: RN: BUGFIX

#4286 Update actions to use latest github hosted runner
  .github/workflows/artifact-links.yml
  .github/workflows/auto-close.yml
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/hide-artifact-links.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
  .github/workflows/translations-pr.yml
  .github/workflows/translations-upload.yml
Labels: build system improvement

#4276 Update IMU (remove legacy)
  src/js/tabs/setup.js
Labels: Needs coordination with firmware, Tested, RN: IMPROVEMENT
