Repository betaflight/betaflight-configurator, pull requests merged in 2024-05, with the labels that each got.

#3925 Adjust header bar in mobile devices
  src/css/main.less
Labels: RN: UI

#3923 Fix dual telemetry in receiver tab for local builds
  src/js/Features.js
Labels: Tested, RN: BUGFIX

#3931 Expose [local] firmware build options
  locales/en/messages.json
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#3933 Fix virtual reboot and auto-connect
  src/js/fc.js
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3823 New led functions gps bar battery bar altitude
  locales/en/messages.json
  src/css/tabs/led_strip.less
  src/js/msp/MSPHelper.js
  src/js/tabs/led_strip.js
  src/tabs/led_strip.html
Labels: Tested, RN: IMPROVEMENT

#3935 Fix AT32 detection
  src/js/port_handler.js
Labels: RN: BUGFIX

#3932 Fix reset options
  src/js/fc.js
  src/js/port_handler.js
Labels: RN: BUGFIX

#3939 Fix MSP Radio emulator in PWA
  src/js/browserReceiverMsp.js
  src/js/tabs/receiver.js
  src/js/tabs/receiver_msp.js
  src/js/utils/window_watchers.js
  src/receiver_msp/index.html
  vite.config.js
Labels: RN: BUGFIX

#3703 Add manual connection option
  locales/en/messages.json
  src/js/port_handler.js
  src/js/serial_backend.js
  src/js/tabs/options.js
  src/tabs/options.html
Labels: Tested, RN: IMPROVEMENT

#3934 Adjust title/name to be in coherence with Blackbox
  package.json
  src/index.html
  vite.config.js
Labels: Housekeeping

#3941 Rename receiver_msp/index.html by receiver_msp/receiver_msp.html
  gulpfile.js
  src/css/receiver_msp/receiver_msp.less
  src/js/browserReceiverMsp.js
  src/js/receiver_msp/receiver_msp.js
  src/js/tabs/receiver.js
  src/receiver_msp/receiver_msp.html
  vite.config.js
Labels: Cleanup

#3944 Updating product name and description
  package.json
  src/index.html
Labels: Housekeeping

#3913 Cli on web
  src/js/tabs/cli.js
  src/tabs/presets/CliEngine.js
Labels: RN: IMPROVEMENT

#3952 Delete .github/workflows/app-build.yml
  .github/workflows/app-build.yml
Labels: Housekeeping

#3954 Update nightly.yml
  .github/workflows/nightly.yml
Labels: Housekeeping

#3953 Update pr.yml
  .github/workflows/pr.yml
Labels: Housekeeping

#3962 Chore/remove nwjs build
  cordova/build_template.json
  cordova/config_template.xml
  cordova/debug.keystore
  cordova/package_template.json
  cordova/usb_device_filter.xml
  cordova/yarn.lock
  gulp-appdmg.js
  gulpfile.js
  package.json
  src/css/main_cordova.less
  src/js/cordova_chromeapi.js
  src/js/cordova_startup.js
  src/js/main_cordova.js
  src/main_cordova.html
  yarn.lock
Labels: Cleanup

#3965 Remove gulp appdmg
  .github/workflows/ci.yml
  README.md
  package.json
Labels: Housekeeping

#3949 Add DFU support for PWA
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/protocols/webusbdfu.js
  src/js/tabs/firmware_flasher.js
  src/js/usb_devices.js
  src/js/usb_shim.js
Labels: Tested, RN: FEATURE

#3966 10.10-maintenance update - including background colour activation cherry pick
  package.json
  src/css/tabs/auxiliary.less
  src/js/data_storage.js
Labels: RN: BUGFIX

#3972 Fix lint issues
  src/components/port-picker/FirmwareVirtualOption.vue
  src/components/port-picker/PortOverrideOption.vue
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/js/port_handler.js
  src/js/webSerial.js
Labels: Cleanup

#3967 Update README to remove building with nw.js
  README.md
Labels: Housekeeping

#3970 Add auto-connect checkbox again
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/js/port_handler.js
  src/js/serial_backend.js
Labels: RN: REFACTOR, PWA

#3927 Add Acro center sensitivity to Betaflight Rates
  locales/en/messages.json
  src/css/tabs/pid_tuning.less
  src/js/tabs/pid_tuning.js
  src/tabs/pid_tuning.html
Labels: RN: IMPROVEMENT

#3975 Sort rate models
  src/js/tabs/firmware_flasher.js
  src/js/tabs/pid_tuning.js
Labels: RN: IMPROVEMENT

#3976 Add CLI file functions for PWA
  src/js/tabs/cli.js
Labels: RN: REFACTOR, PWA

#3938 Add support for gyro_cal_on_first_arm
  locales/en/messages.json
  src/css/tabs/configuration.less
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: FEATURE

#3978 Fix detection of port at boot
  src/components/port-picker/PortsInput.vue
Labels: RN: REFACTOR, PWA

#3968 Use the "show manual" preference in the porthandler to show or hide the option
  locales/en/messages.json
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/index.html
  src/js/port_handler.js
  src/js/tabs/options.js
Labels: RN: REFACTOR, PWA

#3977 Add FileSystem API to read/write files and use it
  locales/en/messages.json
  src/js/FileSystem.js
  src/js/LogoManager.js
  src/js/backup_restore.js
  src/js/gui.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/osd.js
  src/js/tabs/vtx.js
  src/tabs/presets/presets.js
Labels: PWA

#3979 Remove mdns feature
  locales/en/messages.json
  package.json
  src/js/mdns_discovery.js
  src/js/port_handler.js
  src/js/tabs/options.js
  src/tabs/options.html
  yarn.lock
Labels: Cleanup, PWA

#3985 Fix baudrate
  src/js/webSerial.js
Labels: Cleanup, PWA

#3986 Fix reboot
  src/js/gui.js
  src/js/msp/MSPHelper.js
  src/js/port_handler.js
  src/js/serial_backend.js
  src/js/webSerial.js
Labels: RN: BUGFIX, PWA

#3984 Refactor port handler
  src/components/port-picker/PortsInput.vue
  src/js/port_handler.js
  src/js/protocols/stm32.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
  src/js/webSerial.js
Labels: RN: REFACTOR, PWA

#3990 Prevent closing serial twice on reboot
  src/js/webSerial.js
Labels: RN: BUGFIX, PWA

#3991 Add DFU devices to the port handler
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/index.html
  src/js/port_handler.js
  src/js/protocols/webusbdfu.js
  src/js/serial_backend.js
  src/js/webSerial.js
Labels: RN: IMPROVEMENT, PWA

#3992 Move some code of portOverride from serial_backend to vue
  src/components/port-picker/PortOverrideOption.vue
  src/components/port-picker/PortsInput.vue
  src/js/port_handler.js
  src/js/serial_backend.js
Labels: RN: REFACTOR, PWA
