Repository betaflight/betaflight-configurator, pull requests merged in 2024-02, with the labels that each got.

#3767 Disable video modes that are not in the firmware
  src/css/tabs/osd.less
  src/js/tabs/osd.js
Labels: Tested, RN: UI

#3781 Fix port picker trigger event
  src/js/port_handler.js
Labels: RN: BUGFIX

#3786 Fix Accelerometer units
  locales/ca/messages.json
  locales/da/messages.json
  locales/de/messages.json
  locales/en/messages.json
  locales/es/messages.json
  locales/eu/messages.json
  locales/fr/messages.json
  locales/gl/messages.json
  locales/it/messages.json
  locales/ja/messages.json
  locales/ko/messages.json
  locales/nl/messages.json
  locales/pl/messages.json
  locales/pt/messages.json
  locales/pt_BR/messages.json
  locales/uk/messages.json
  locales/zh_CN/messages.json
Labels: RN: UI

#3787 Bump workflow actions
  .github/workflows/app-build.yml
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/translations-pr.yml
  .github/workflows/translations-upload.yml
Labels: build system improvement

#3790 Don't trigger font upload when enter is pressed in alarm time field
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3792 Fix missing mag
  src/js/tabs/setup.js
Labels: RN: BUGFIX

#3794 Bump remaining workflow actions to v4
  .github/workflows/app-build.yml
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: build system improvement

#3779 Update timing-accuracy debug field.
  src/js/debug.js
Labels: RN: IMPROVEMENT

#3793 Prevent issues with corrupted firmware using outdated configurator
  locales/en/messages.json
  src/js/serial_backend.js
  src/js/utils/checkForConfiguratorUpdates.js
Labels: RN: BUGFIX

#3800 Update serialrx_provider table
  src/js/fc.js
  src/js/tabs/receiver.js
Labels: RN: BUGFIX

#3770 Redesign of Firmware section at Setup tab
  locales/en/messages.json
  src/css/dark-theme.less
  src/css/tabs/setup.less
  src/js/tabs/setup.js
  src/main.html
  src/tabs/setup.html
Labels: RN: UI

#3801 Fix mag declination
  src/js/msp/MSPHelper.js
  src/js/tabs/gps.js
Labels: RN: BUGFIX

#3803 Fix reset dialog
  src/css/tabs/setup.less
Labels: RN: UI

#3805 modify "Reset" verbiage
  locales/en/messages.json
Labels: RN: UI

#3749 App Build - disable push AWS on forks
  .github/workflows/app-build.yml
Labels: Housekeeping

#3804 Remove event listener for flashing using Enter key.
  src/js/tabs/firmware_flasher.js
  src/tabs/firmware_flasher.html
Labels: RN: UI

#3811 Fix missing PID filter slider labels
  src/tabs/pid_tuning.html
Labels: RN: UI

#3815 set latest vtx_power to prevent out of boundary error
  src/js/tabs/vtx.js
Labels: RN: BUGFIX

#3813 Fix light mode
  src/css/tabs/pid_tuning.less
Labels: Cleanup

#3816 Fix changing blackbox rate for 4.2 and older firmware
  src/js/tabs/onboard_logging.js
Labels: RN: BUGFIX

#3822 Fix messages and layout
  src/js/tabs/setup.js
Labels: Cleanup
