Repository betaflight/betaflight-configurator, pull requests merged in 2024-07, with the labels that each got.

#4076 Fix hide of dataflash element
  src/css/main.less
Labels: RN: UI

#4077 Fix botton toolbar again in modes an flasher tab
  src/css/tabs/auxiliary.less
  src/css/tabs/firmware_flasher.less
Labels: RN: UI

#4079 Fix typos
  locales/en/messages.json
Labels: RN: UI

#4080 Update AutoBackup.js to use diff all
  src/js/utils/AutoBackup.js
Labels: Cleanup

#4081 Detect GitHub branch name automatically from URL
  src/tabs/presets/SourcesDialog/PresetSource.js
  src/tabs/presets/SourcesDialog/SourcePanel.js
Labels: RN: IMPROVEMENT

#4082 Fix auto_disarm_delay being reset
  src/js/tabs/configuration.js
Labels: RN: BUGFIX

#4083 Fixes text legibility
  src/css/main.less
Labels: RN: UI

#4086 Style Fix: Adjust layout for fixed toolbar
  src/css/main.less
  src/css/tabs/cli.less
  src/css/tabs/logging.less
  src/css/tabs/motors.less
  src/css/tabs/ports.less
  src/tabs/cli.html
  src/tabs/logging.html
  src/tabs/motors.html
Labels: RN: UI

#4094 Fix CLI buttons
  src/js/tabs/cli.js
Labels: RN: BUGFIX

#4092 Fixed text color in motors & PID tabs for light mode
  src/css/tabs/motors.less
  src/css/tabs/pid_tuning.less
Labels: RN: UI

#4090 Fix menu overflow
  src/css/main.less
Labels: RN: UI

#4088 Little cleanup
  src/js/tabs/configuration.js
  src/js/tabs/pid_tuning.js
  src/tabs/configuration.html
  src/tabs/pid_tuning.html
Labels: Cleanup

#3998 Extract out virtual serial
  src/js/Clipboard.js
  src/js/main.js
  src/js/msp/MSPConnector.js
  src/js/port_usage.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/serial_shim.js
  src/js/tabs/cli.js
  src/js/tabs/sensors.js
  src/js/tabs/vtx.js
  src/js/virtualSerial.js
Labels: RN: REFACTOR, PWA

#4096 Fix ELRS UUID
  src/js/tabs/receiver.js
Labels: RN: BUGFIX

#4098 Fix feedforward smooth factor range
  src/tabs/pid_tuning.html
Labels: RN: BUGFIX

#4097 Hide firmware version dropdown for virtual mode
  src/components/port-picker/PortPicker.vue
  src/js/serial_backend.js
  src/main.html
Labels: RN: UI

#4099 [10.10-MAINT] Fix feedforward smooth factor range
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#4100 [10.10-MAINT] update macos build
  .github/workflows/ci.yml
Labels: build system improvement, Housekeeping

#4101 Remove main.html
  package.json
  src/main.html
Labels: Cleanup, PWA

#4102 Fix configuratorUpdateHelp message
  locales/en/messages.json
Labels: Cleanup

#3940 Enforce preset mutally exclusive option groups
  src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
  src/tabs/presets/PresetsRepoIndexed/PresetParser.js
Labels: RN: IMPROVEMENT

#4103 Fix autodetect for some older 4.5 firmware builds
  src/js/utils/AutoDetect.js
Labels: Cleanup

#4000 Remove cordova logic
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/js/DarkTheme.js
  src/js/gui.js
  src/js/main.js
  src/js/phones_ui.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/options.js
  src/js/tabs/osd.js
  src/js/tabs/receiver.js
  src/js/tabs/vtx.js
  src/tabs/presets/presets.js
Labels: RN: REFACTOR, PWA

#4104 Add ELRS SPI Model Match ID
  locales/en/messages.json
  src/js/msp/MSPHelper.js
  src/js/tabs/receiver.js
  src/tabs/receiver.html
Labels: RN: IMPROVEMENT

#4109 Update TPA debug fields
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4108 Change displaying of instruments in the setup tab.
  src/css/tabs/setup.less
Labels: RN: UI

#4112 Vertically centered label and its radiobutton in OSD tab
  src/css/tabs/osd.less
Labels: RN: UI

#4113 Use basic less functions to generate repeated css
  src/css/main.less
Labels: RN: IMPROVEMENT

#4115 Adjust contrast ratio for sidebar links. Add flexible colors for svg.
  src/css/main.less
Labels: RN: UI

#4117 Remove right margin for .helpicon in .gui_box_titlebar
  src/css/main.less
Labels: RN: UI
