Repository betaflight/betaflight-configurator, pull requests merged in 2024-04, with the labels that each got.

#3862 Update board wiki URL
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: UI

#3826 Add EZLANDING debug field
  src/js/debug.js
Labels: RN: IMPROVEMENT

#3865 Fix compass calibration interval timeout
  src/js/tabs/setup.js
Labels: RN: BUGFIX

#3875 Fix failsafe delay constraints
  src/tabs/failsafe.html
Labels: RN: BUGFIX

#3879 Throttle curve now respects throttle scale and clip
  src/js/fc.js
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#3883 Make the dark / light theme work with PWA
  src/css/dark-theme.less
  src/js/DarkTheme.js
  src/main.html
Labels: RN: BUGFIX

#3705 Clarify GPS Signal Strength
  locales/en/messages.json
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: UI

#3886 Add PWA link to unstable versions of the Configurator on README
  README.md
Labels: Housekeeping

#3884 Add additional installation steps for Ubuntu 23.10
  README.md
Labels: documentation update, Housekeeping

#3888 Adding rotation of the sponsor logos.
  src/js/BuildApi.js
  src/js/Sponsor.js
Labels: RN: IMPROVEMENT

#3890 FIX: Incorrect format for the tracking call.
  src/js/DarkTheme.js
  src/js/main.js
Labels: Cleanup, RN: BUGFIX

#3889 Remove nightly and weekly app builds.
  .github/workflows/app-nightly.yml
  .github/workflows/app-weekly.yml
  .github/workflows/build-release.yml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
  .github/workflows/translations-pr.yml
Labels: Cleanup, RN: BUILD SYSTEM

#3894 Fix OSD timer
  src/js/tabs/osd.js
Labels: RN: BUGFIX

#3895 Smoothing transition while refreshing sponsor icons
  src/js/Sponsor.js
Labels: RN: UI

#3899 Fix buildkey 404
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#3901 Fix intermittent race condition
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3900 Use firmware options on introduction
  src/js/Features.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: Tested, RN: IMPROVEMENT

#3905 Rename blackbox field entry "Unfiltered Gyro"
  src/js/debug.js
Labels: RN: UI

#3903 Fix column width
  src/css/tabs/logging.less
Labels: RN: UI

#3908 Fix connection for patch release versions
  src/js/serial_backend.js
Labels: RN: BUGFIX

#3909 More Space Between Sponsors
  src/css/main.less
Labels: Cleanup

#3910 Add angle mode center sensitivity
  src/js/tabs/pid_tuning.js
Labels: Tested, RN: IMPROVEMENT

#3914 Fix Angle Mode positioning
  src/js/tabs/pid_tuning.js
Labels: Cleanup, Tested

#3873 Update version to 11.0
  package.json
  src/js/data_storage.js
Labels: For Discussion, Housekeeping

#3882 Feat/web virtual mode
  src/components/eventBus.js
  src/components/init.js
  src/components/port-picker/FirmwareVirtualOption.vue
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/index.html
  src/js/ConfigStorage.js
  src/js/msp.js
  src/js/port_handler.js
  src/js/serial_backend.js
  src/js/serial_shim.js
Labels: RN: FEATURE

#3872 Update yarn.lock versions
  yarn.lock
Labels: dependencies

#3922 Update link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Housekeeping

#3916 Fix virtual mode after serial connection
  src/js/VirtualFC.js
Labels: RN: BUGFIX

#3887 Add clipboard feature to web app
  resources/jsonschema/vtxconfig_schema-1.0.json
  src/js/Clipboard.js
  src/js/tabs/vtx.js
Labels: RN: IMPROVEMENT
