Repository betaflight/betaflight-configurator, pull requests merged in 2025-07, with the labels that each got.

#4540 Prevent GATT operation in progress
  src/js/protocols/WebBluetooth.js
Labels: RN: BUGFIX

#4544 Add support ID to clipboard
  src/js/tabs/cli.js
Labels: RN: IMPROVEMENT

#4546 docs (motorsTelemetryHelp): spelling fix and add of denomination info…
  locales/en/messages.json
Labels: RN: BUGFIX

#4547 Fix: Handle BT-11 BLE boards
  src/js/msp.js
  src/js/protocols/WebBluetooth.js
  src/js/protocols/devices.js
Labels: RN: BUGFIX

#4554 Fix manual protocol selection
  src/js/serial.js
Labels: Tested, RN: BUGFIX

#4557 Add beeper-config controls
  locales/en/messages.json
  src/css/tabs/configuration.less
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: RN: IMPROVEMENT

#4560 🔧 Abort when already connected
  src/js/serial_backend.js
Labels: RN: BUGFIX
