Repository betaflight/betaflight-configurator, pull requests merged in 2025-01, with the labels that each got.

#4290 Display either flash or sdcard
  src/js/serial_backend.js
  src/js/update_dataflash_global.js
Labels: RN: BUGFIX

#4292 Add position hold build option
  src/js/fc.js
Labels: RN: IMPROVEMENT

#4293 Update dependencies
  package.json
  yarn.lock
Labels: dependencies

#4294 Add gyro and magnetic custom alignment MSP
  locales/en/messages.json
  src/css/tabs/configuration.less
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/js/tabs/gps.js
  src/tabs/configuration.html
  src/tabs/gps.html
Labels: Needs coordination with firmware, RN: IMPROVEMENT

#4299 Updating MCU type list to maintain sync with firmware
  src/js/fc.js
Labels: RN: BUGFIX

#4297 pre-arm recommendation
  locales/en/messages.json
Labels: RN: IMPROVEMENT

#4302 Add IIM42653 IMU
  src/js/tabs/setup.js
Labels: RN: IMPROVEMENT

#4303 Add binary sub protocol to allow communication with websockify.
  src/js/protocols/websocket.js
Labels: RN: IMPROVEMENT

#4304 Fix socket reset
  src/js/protocols/websocket.js
  src/js/serial_backend.js
Labels: RN: BUGFIX

#4306 Add MCU_INFO MSP support
  locales/en/messages.json
  src/js/fc.js
  src/js/msp/MSPCodes.js
  src/js/msp/MSPHelper.js
  src/js/serial_backend.js
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#4305 Update sonar elements
  src/js/tabs/setup.js
Labels: RN: IMPROVEMENT

#4308 Dynamic “return altitude” field in GPS Rescue tab
  locales/en/messages.json
  src/js/tabs/failsafe.js
Labels: RN: IMPROVEMENT

#4317 Add 230K4 baudrate support for GPS
  src/js/tabs/ports.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT
