Repository betaflight/betaflight-configurator, pull requests merged in 2025-08, with the labels that each got.

#4565 Add MSP_STATUS_EX to catch rate profile number
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#4564 REFACTOR: Implement Fetch over $.ajax
  src/js/BuildApi.js
  src/js/Sponsor.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/utils/AutoDetect.js
Labels: Tested, RN: REFACTOR

#4549 Cleanup unused imports + update eslint configuration
  eslint.config.js
  package.json
  src/components/EscDshotDirection/EscDshotDirectionComponent.js
  src/js/CliAutoComplete.js
  src/js/DarkTheme.js
  src/js/tabs/cli.js
  src/js/tabs/onboard_logging.js
  yarn.lock
Labels: Cleanup, dependencies

#4570 Clarify cli (dev only) mode
  locales/en/messages.json
  src/js/tabs/cli.js
Labels: RN: IMPROVEMENT

#4576 Fix Port Utilization
  src/components/status-bar/PortUtilization.vue
  src/js/port_usage.js
Labels: RN: BUGFIX

#4578 Fix typo
  src/js/tabs/setup.js
Labels: Cleanup

#4581 Fix typo
  src/js/TuningSliders.js
  src/js/main.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/setup.js
  src/js/utils/isExpertModeEnabled.js
Labels: Cleanup
