Repository betaflight/betaflight-configurator, pull requests merged in 2025-09, with the labels that each got.

#4584 PRE-RELEASE: Preparing for CalVer change
  .gitignore
  .prettierignore
  .travis.yml
  locales/en/messages.json
  package.json
Labels: RN: BUILD SYSTEM

#4585 Updating Privacy Policy for App
  src/tabs/privacy_policy.html
Labels: RN: IMPROVEMENT

#4583 TARGET: Implement simple ability to flash UF2 for PICO
  locales/en/messages.json
  src/js/BuildApi.js
  src/js/protocols/devices.js
  src/js/tabs/firmware_flasher.js
Labels: RN: FEATURE, RN: BUILD SYSTEM

#4597 Quick fix for Chromium v140 select issue
  src/js/utils/common.js
Labels: RN: BUGFIX

#4590 Remove IMU alignment from UI
  locales/en/messages.json
  src/css/tabs/configuration.less
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/configuration.js
  src/tabs/configuration.html
Labels: Cleanup, Needs coordination with firmware, RN: REFACTOR

#4624 Fix custom mag_alignment
  src/js/msp/MSPHelper.js
Labels: RN: BUGFIX

#4616 Style: Fix various small UI inconsistencies
  src/css/main.less
  src/css/tabs/configuration.less
  src/css/tabs/landing.less
  src/css/tabs/motors.less
  src/css/tabs/pid_tuning.less
  src/css/tabs/setup.less
  src/js/tabs/configuration.js
  src/js/tabs/gps.js
  src/tabs/configuration.html
  src/tabs/gps.html
  src/tabs/motors.html
  src/tabs/pid_tuning.html
  src/tabs/presets/presets.less
  src/tabs/setup.html
Labels: RN: UI
