Repository betaflight/betaflight-configurator, pull requests merged in 2025-06, with the labels that each got.

#4492 Update sensor_types.js (ICM40609D)
  src/js/sensor_types.js
Labels: RN: IMPROVEMENT

#4503 Fix duplicate ID
  src/components/EscDshotDirection/Body.html
Labels: Cleanup

#4497 Represent OSD font characters using text/SVG instead of canvas/PNG for better performance (OSD tab loads in roughly half the time on an older Chromebook).
  src/js/tabs/osd.js
Labels: RN: IMPROVEMENT

#4514 Fix violation in motor slider events
  src/js/tabs/motors.js
Labels: RN: BUGFIX

#4507 Fix intermittent mouseover handler undefined issue
  src/js/CliAutoComplete.js
Labels: RN: BUGFIX

#4517 Fix: Add null checks for search parameters, allowing proper functiona…
  src/tabs/presets/presets.js
Labels: RN: BUGFIX

#4500 cleanup and explicit use web prefix for protocols
  src/components/port-picker/PortsInput.vue
  src/js/data_storage.js
  src/js/port_handler.js
  src/js/protocols/WebBluetooth.js
  src/js/protocols/WebSerial.js
  src/js/serial.js
  src/js/serial_backend.js
  src/js/utils/checkBrowserCompatibility.js
Labels: RN: REFACTOR

#4509 Fix missing callback
  src/js/protocols/WebBluetooth.js
  src/js/protocols/WebSocket.js
Labels: RN: BUGFIX

#4518 Feature: Add modified loader to load arbitrary html as Vue apps
  src/components/init.js
  src/js/vue_components.js
  src/js/vue_loader.js
Labels: RN: FEATURE

#4520 Make loading GL transform less verbose
  src/js/model.js
Labels: Cleanup

#4525 UI: Reduce size of switchery selectors
  src/css/switchery_custom.less
Labels: RN: UI

#4524 REFACTOR: Removing a number of tracking events (superfluous) and combining others.
  src/js/Analytics.js
  src/js/CliAutoComplete.js
  src/js/DarkTheme.js
  src/js/main.js
  src/js/serial_backend.js
  src/js/tabs/cli.js
  src/js/tabs/firmware_flasher.js
  src/js/tabs/onboard_logging.js
  src/js/tabs/options.js
  src/js/tabs/vtx.js
Labels: RN: REFACTOR

#4521 PICO: Adding USB serial filter for PICO boards
  src/js/protocols/WebSerial.js
  src/js/protocols/devices.js
Labels: RN: IMPROVEMENT

#4516 UI : Preset positioning for elements in OSD
  src/css/tabs/osd.less
  src/js/tabs/osd.js
Labels: RN: IMPROVEMENT

#4529 Fix webserial device not found
  src/js/protocols/WebSerial.js
  src/js/tabs/firmware_flasher.js
Labels: RN: BUGFIX

#4484 Replace all 4 instances of jBox-style modal dialog boxes with HTML dialog element
  locales/en/messages.json
  src/css/main.less
  src/css/tabs/cli.less
  src/css/tabs/osd.less
  src/js/main.js
  src/js/tabs/cli.js
  src/js/tabs/osd.js
  src/js/tabs/power.js
  src/js/utils/initializeModalDialog.js
  src/tabs/cli.html
  src/tabs/osd.html
  src/tabs/power.html
  test/setup.js
Labels: RN: REFACTOR

#4532 Fix virtual modes / messages
  locales/en/messages.json
  src/js/VirtualFC.js
Labels: RN: BUGFIX

#4533 Fix OSD search
  src/js/tabs/osd.js
Labels: RN: BUGFIX
