Repository betaflight/betaflight-configurator, pull requests merged in 2025-05, with the labels that each got.

#4450 Add Firmware/Download to Setup tab, add ':', formatting (#4444)
  locales/en/messages.json
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#4454 Add DroneBridge Bluetooth LE device definition
  src/js/protocols/devices.js
Labels: RN: IMPROVEMENT

#4449 Fix serial
  src/js/protocols/WebSerial.js
  src/js/serial.js
  src/js/utils/AutoDetect.js
Labels: RN: BUGFIX, RN: REFACTOR

#4456 Update OS check
  src/js/gui.js
  src/js/utils/checkBrowserCompatibilty.js
Labels: RN: IMPROVEMENT

#4457 Ensure single comment is created
  .github/workflows/deploy-preview.yml
Labels: Housekeeping

#4458 Add coderabbit config
  .coderabbit.yaml
  netlify.toml
Labels: Housekeeping

#4460 Update Setup tab to hide build type/info/firmware when not available (#4459)
  src/js/tabs/setup.js
Labels: RN: IMPROVEMENT

#4455 Fix AT32 Configuration can't be saved on MacOS
  src/js/protocols/WebSerial.js
  src/js/utils/checkBrowserCompatibilty.js
Labels: RN: BUGFIX

#4469 Remove last references to chrome.app
  src/js/DarkTheme.js
  src/js/receiver_msp/receiver_msp.js
  src/js/utils/common.js
  src/js/utils/window_watchers.js
Labels: Cleanup, RN: REFACTOR

#4470 Allow execution when either Web Serial, Bluetooth or USB API is present
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/index.html
  src/js/gui.js
  src/js/port_handler.js
  src/js/protocols/WebBluetooth.js
  src/js/protocols/WebSerial.js
  src/js/protocols/webusbdfu.js
  src/js/utils/checkBrowserCompatibility.js
Labels: RN: IMPROVEMENT

#4468 fix preview checkout
  .github/workflows/deploy-preview.yml
Labels: Housekeeping

#4475 Update deploy-preview.yml for short sha
  .github/workflows/deploy-preview.yml
Labels: Housekeeping

#4387 [10.10.1] macos-13 github runner
  .github/workflows/ci.yml
Labels: build system improvement

#4478 Fix throttle curve backwards compatibility
  src/js/tabs/pid_tuning.js
Labels: RN: BUGFIX

#4483 Include support ID when saving to file
  src/js/tabs/cli.js
Labels: RN: IMPROVEMENT

#4489 Reduce confusion selecting VTX
  src/js/tabs/ports.js
Labels: RN: BUGFIX

#4432 Add support for ICM45605 and ICM45686
  src/js/sensor_types.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT
