Repository betaflight/betaflight-configurator, pull requests merged in 2025-02, with the labels that each got.

#4329 modify ALTITUDE_HOLD mode verbiage
  locales/en/messages.json
Labels: RN: IMPROVEMENT

#4330 update eslint-config-prettier@^10.0.1
  package.json
  yarn.lock
Labels: dependencies

#4324 Ports-tab SerialRX help-tip
  locales/en/messages.json
  src/css/tabs/ports.less
  src/tabs/ports.html
Labels: RN: IMPROVEMENT

#4331 Add support for conditional number of rate profiles (msp)
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/pid_tuning.js
Labels: Needs coordination with firmware, RN: IMPROVEMENT

#4332 update virtualFC version and accompanying modes for modes-tab
  src/components/port-picker/FirmwareVirtualOption.vue
  src/js/VirtualFC.js
  src/js/port_handler.js
  src/js/utils/common.js
Labels: RN: IMPROVEMENT

#4340 Add CHIRP debug mode
  src/js/debug.js
Labels: RN: IMPROVEMENT

#4338 don't translate single variable messages
  locales/en/messages.json
Labels: RN: TRANSLATION

#4336 Add magnetic declination info
  locales/en/messages.json
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#4334 Add array mutation helper and add missing arming disable flags
  src/js/VirtualFC.js
  src/js/debug.js
  src/js/sensor_types.js
  src/js/tabs/setup.js
  src/js/utils/array.js
Labels: RN: REFACTOR

#4343 Add visual info about pdop quality
  locales/en/messages.json
  src/css/main.less
  src/js/tabs/gps.js
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#4319 Reducing the minumum mmix number of motors for the warning to appear in the "Custom Airplane" mixer
  src/js/model.js
Labels: RN: IMPROVEMENT

#4341 Add missing tooltips (ALTHOLD, POSHOLD)
  locales/en/messages.json
Labels: RN: IMPROVEMENT

#4326 Disable motor stop feature when airmode is enabled
  locales/en/messages.json
  src/css/switchery_custom.less
  src/js/Features.js
  src/js/tabs/motors.js
Labels: RN: IMPROVEMENT

#4344 Improve configuration for MSP GNSS
  locales/en/messages.json
  src/css/tabs/gps.less
  src/js/Features.js
  src/js/VirtualFC.js
  src/js/tabs/configuration.js
  src/js/tabs/gps.js
  src/js/utils/updateTabList.js
  src/tabs/gps.html
Labels: RN: IMPROVEMENT

#4351 Fix Three.js no WebGL mode
  locales/en/messages.json
  src/js/model.js
  src/js/tabs/options.js
  src/js/utils/three/CanvasRenderer.js
  src/js/utils/three/Projector.js
  src/tabs/options.html
  vite.config.js
  yarn.lock
Labels: RN: IMPROVEMENT

#4258 Update Vue
  package.json
  src/components/data-flash/DataFlash.vue
  src/components/eventBus.js
  src/components/init.js
  src/components/port-picker/FirmwareVirtualOption.vue
  src/components/port-picker/PortOverrideOption.vue
  src/components/port-picker/PortPicker.vue
  src/components/port-picker/PortsInput.vue
  src/components/quad-status/BatteryIcon.vue
  src/components/quad-status/BatteryLegend.vue
  src/components/quad-status/BottomStatusIcons.vue
  src/components/sensor-status/SensorStatus.vue
  src/components/status-bar/PortUtilization.vue
  src/components/status-bar/ReadingStat.vue
  src/components/status-bar/StatusBar.vue
  src/components/status-bar/StatusBarVersion.vue
  src/components/vueI18n.js
  src/js/fc.js
  src/js/port_handler.js
  vite.config.js
  yarn.lock
Labels: dependencies

#4354 Improve debug logging
  src/js/port_handler.js
  src/js/protocols/bluetooth.js
  src/js/protocols/websocket.js
  src/js/protocols/webstm32.js
  src/js/protocols/webusbdfu.js
  src/js/serial_backend.js
  src/js/tabs/firmware_flasher.js
Labels: RN: REFACTOR

#4349 Update latlon
  locales/en/messages.json
  src/js/VirtualFC.js
  src/js/fc.js
  src/js/msp/MSPHelper.js
  src/js/tabs/gps.js
  src/js/tabs/setup.js
  src/tabs/gps.html
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#4357 Need expert mode for reset
  locales/en/messages.json
  src/js/tabs/setup.js
  src/tabs/setup.html
Labels: RN: IMPROVEMENT

#4356 Fixed collapsed sidebar
  src/css/main.less
Labels: RN: BUGFIX

#4359 Update capacitor and browser compat check
  .gitattributes
  .gitignore
  android/app/capacitor.build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  package.json
  src/js/utils/checkBrowserCompatibilty.js
  yarn.lock
Labels: dependencies

#4363 Fix macOS useragentdata check
  src/js/utils/checkBrowserCompatibilty.js
Labels: Tested, RN: BUGFIX

#4364 Fix motorIdle being hidden in previous versions
  src/js/tabs/motors.js
Labels: RN: BUGFIX
